### ISSUE TITLE
Include "type" information

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#1]
The JSON schema provides information regarding the “type” i.e., whether an item is a string, integer or float. This information need to be presented while adding new rows to a table.

**Comment by ytfqj** [comment]
Is it OK to show in "comment" together with 'description'?

**Comment by brindakv** [comment]
It can be shown along with the description in the comment or along with the column name.

**Comment by hongsudt** [comment]
This has been implemented.
