### ISSUE TITLE
Change ACL for `Entry.Record_Status_Detail`

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#103]
`pdb-submitter` needs to be able to see the error messages. 

Column header should be shown as `Record Status Detail`.

**Comment by svoinea** [comment]
The `pdb-submitter` is able now to see the `Record Status Detail` on all the catalogs.
On `dev.pdb-dev.org` (catalog `99`) the column name is shown now  as` Record Status Detail`.

**Comment by brindakv** [comment]
User is able to see the error messages on dev and production. The column header is shown as `Record Status Detail` on catalog 99 and can be moved to production.
