### ISSUE TITLE
Update text for error messages in Record_Status_Detail

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#104]
Common errors: 
- Duplicate entries created when re-uploading files
- python-ihm related errors (with traceback message): add a leading sentence `Error from python-ihm`

**Comment by svoinea** [comment]
On `dev.pdb-dev.org` (catalog `99`), the `Record Status Detail` will contain now a short error message, while the stack trace will remain in the body of the mail message.

**Comment by brindakv** [comment]
The error message is shown in full in the detailed view and in the email. The compact view has a truncated message. See `RID=1-WQWP` on `dev`.

**Comment by brindakv** [comment]
@svoinea will check the error handling during `Submit`--> `mmCIF Created` and `Release Ready` --> `REL`. Are the processes for mmCIF generation and validation (and the corresponding errors) handled in the same manner in the two workflow steps? 
Note: `Depo` --> `Record Ready` no mmCIF is created or validated (although make-mmcif.py is used). 

Anytime mmCIF is created, it should be validated.  

Refer to #94, #73, and #107  

Can we classify the errors and provide a more meaningful message to users? 
 - Errors generated during `make-mmcif.py` is stored in ermRest (no log files) and shown in full
 - Error during mmCIF validation (cpp-dict-pack) is stored in hatrac (log) files that are linked from ermRest
 - All other error messages that do not call an external script will contain now a short error message, while the stack trace will remain in the body of the email message

@brindakv will test to make sure that the above scenario is true. 

Consider moving workflow error messages to a new table to keep track of history.

**Comment by brindakv** [comment]
> 1. Errors generated during make-mmcif.py is stored in ermRest (no log files) and shown in full. 
> 2. Error during mmCIF validation (cpp-dict-pack) is stored in hatrac (log) files that are linked from ermRest. 
> 3. All other error messages that do not call an external script will contain now a short error message, while the stack trace will remain in the body of the email message. 

The first two are correct. Not sure how to test the third one.

**Comment by svoinea** [comment]
Short error messages will mostly appear in `loadTablesFromJSON` and/or `loadTableFromCVS` (examples `duplicates` or missing values for `NOT NULL` columns).

Seldom, they might appear from `ermrest` and/or `hatrac` (examples `File not found in hatrac`, `Can not insert a row`, `Can not generate an accession code`).

**Comment by brindakv** [comment]
@brindakv tested and verified on catalog `99`.

**Comment by svoinea** [comment]
The `dev` branch was merged, the new release `pdb-20221130.1` was created and deployed on production.

**Comment by brindakv** [comment]
Tested some but not all cases on production.
