### ISSUE TITLE
Update Vocab: Process_Status

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#105]
Update the description and order of rows in https://dev.pdb-dev.org/chaise/recordset/#99/Vocab:Process_Status@sort(RID)

1.  New (trigger backend process)         New record created
2.  Reprocess (trigger backend process after Error)      Status reset to rerun the last backend process (after fixing error)
3.  Success          Last backend process successful 
4.  Resume (trigger backend process)         Workflow resumed (triggered after SUBMIT, SUBMISSION COMPLETE, RELEASE READY)
5.  In progress: processing uploaded mmCIF file       Uploaded mmCIF file is processing after user triggers DEPO
6.  In progress: generating mmCIF file              Generating mmCIF file in progress after user triggers SUBMIT
7.  In progress: generating accession code      Generating accession code in progress after curator triggers SUBMISSION COMPLETE
8.  In progress: releasing entry                           Pre-release process in progress after curator triggers RELEASE READY
9.  Error: processing uploaded mmCIF file         Error processing uploaded mmCIF file after user triggers DEPO
10.  Error: generating mmCIF file                         Error generating mmCIF file after user triggers SUBMIT
11.  Error: generating accession code                 Error generating accession code after curator triggers SUBMISSION COMPLETE
12.  Error: releasing entry                                     Error releasing entry after curator triggers RELEASE READY
13.  In progress: processing uploaded restraint files       Uploaded restraint file is processing after user triggers DEPO
14.  Error: processing uploaded restraint files                  Error processing uploaded restraint file after user triggers DEPO

**Comment by svoinea** [comment]
Done on catalog `99`.

**Comment by brindakv** [comment]
@svoinea The description is updated and the column `RANK` is included. However, the default view should also include sorting by increasing order of the value in `RANK`.

**Comment by svoinea** [comment]
@brindakv If you go through the menu `Vocabulary` --> `Workflow` --> `Process Status`, it comes already sorted by the `Rank` column.

**Comment by brindakv** [comment]
Got it, thanks. Looks good.
