### ISSUE TITLE
Chaise - Add Record - Molecular Features Polymeric Residues Table

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#106]
There is an issue with the chaise form while trying to add a new record to the `Molecular Features - Polymeric Residues` table. 

By definition, the column `Entity Id` is mandatory but the column `Asym Id` is optional in this table. But the form allows user to provide `Asym Id` but not `Entity Id` (see attached photo). After filling in the `Asym Id` the corresponding `Entity Id` is automatically populated in the database (see attached photo). 

This behavior is inconsistent with the data model because `Asym Id` is optional but `Entity Id` is mandatory and the user should be allowed to choose `Entity Id` without choosing `Asym Id`. 

![Screen Shot 2022-09-06 at 10 52 17 PM](https://user-images.githubusercontent.com/15000874/188782793-4712e335-3ebe-4821-887b-439d3db951d6.png)
![Screen Shot 2022-09-06 at 10 52 45 PM](https://user-images.githubusercontent.com/15000874/188782804-7ae114a3-3989-45a3-945c-27cbc63a7673.png)

**Comment by svoinea** [comment]
The table `ihm_poly_residue_feature` has defined the following foreign keys:
```
FOREIGN KEY (structure_id, entity_id, seq_id_begin, comp_id_begin) REFERENCES "PDB".entity_poly_seq(structure_id, entity_id, num, mon_id)
FOREIGN KEY (structure_id, entity_id, seq_id_end, comp_id_end) REFERENCES "PDB".entity_poly_seq(structure_id, entity_id, num, mon_id) 

FOREIGN KEY (structure_id, asym_id) REFERENCES "PDB".struct_asym(structure_id, id) ON UPDATE CASCADE ON DELETE SET NULL
FOREIGN KEY ("Asym_RID", asym_id) REFERENCES "PDB".struct_asym("RID", id) ON UPDATE CASCADE ON DELETE SET NULL
```
Those foreign keys have defined the annotation:
```
"domain_filter_pattern": "{{#if _structure_id}}structure_id={{{_structure_id}}}{{/if}}"
```
When you create a new record:
 - The column `structure_id` gets automatically populated with the value `entry.id`
 - When you select values for the `Polymeric Residue Begin` and `Polymeric Residue End`, the choices are filtered by the `structure_id`. These choices are setting the value for the `entity_id`.
 - Optionally you can select a value for the `asym_id`.

Therefore, as you can see from the foreign keys definitions, `asym_id` is **independent** of the `entity_id` and the value for the `entity_id` is set by the `Polymeric Residue Begin` and `Polymeric Residue End`,

**Comment by brindakv** [comment]
Thanks for the clarification, @svoinea.

**Comment by brindakv** [comment]
@brindakv will test whether two different `entity_ids` are allowed for `Polymeric Residue Begin` and `Polymeric Residue End` and check if there is an open issue to address this. The solution is to include `RID` in the composite fkey. Not sure if this has been systematically implemented (@brindakv to check old issues).

**Comment by brindakv** [comment]
Two different `entity_ids` are not allowed for `Polymeric Residue Begin` and `Polymeric Residue End`. See attached screenshot. 

![Image](https://user-images.githubusercontent.com/15000874/191891755-e33206e7-0028-4237-bc01-9d6a3399af11.png)
