### ISSUE TITLE
Segment mispelled in 3 places

### ISSUE THREAD

**Issue by monica81567** [informatics-isi-edu/protein-database#110]
I noticed that there is a typo under Details of Structural Assemblies* Entity Poly Segement Id should be Entity Poly Segment Id (segment is spelled wrong)

Same with Starting Structural Models* Entity Poly Segement Id and Details of Model Representations* Entity Poly Segement Id and  Localization Density Files Segement Id

**Comment by svoinea** [comment]
Already fixed through the annotations.

**Comment by monica81567** [comment]
Looks good!  Thanks for implementing so quickly.
