### ISSUE TITLE
Session time out

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#112]
@svoinea will increase the setting time out to the maximum allowed.

**Comment by svoinea** [comment]
The current value for `session_expiration_minutes` is `60`. Should I increase it to `120`?

**Comment by monica81567** [comment]
Yes, please increase it to 120.  Thank you.

**Comment by svoinea** [comment]
The session expire time was set to `120`.

**Comment by brindakv** [comment]
Thank you @svoinea.
