### ISSUE TITLE
mmCIF file creation procedure - geometric objects

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#113]
`_ihm_geometric_object_transformation.rot_matrix_1_1` (and other elements of the transformation matrix) should be written as `_ihm_geometric_object_transformation.rot_matrix[1][1]` in the mmCIF file according to the [IHM-dictionary](https://mmcif.wwpdb.org/dictionaries/mmcif_ihm.dic/Categories/ihm_geometric_object_transformation.html). 

Column names in the following two tables need to be changed: 

 `ihm_2dem_class_average_fitting`
 `ihm_geometric_object_transformation`

The columns to be renamed are:

`rot_matrix_1_1` should be changed to `rot_matrix[1][1]` (and all other elements of the 3X3 matrix)
`tr_vector_1` should be changed to `tr_vector[1]` (and all other elements of the 1X3 vector)

**Comment by svoinea** [comment]
The columns were renamed on catalog `99`.

**Comment by brindakv** [comment]
Looks good on catalog `99`. Can be moved to staging and production.

**Comment by svoinea** [comment]
The columns were renamed on staging and production.

**Comment by brindakv** [comment]
Thanks @svoinea. Looks good.
