### ISSUE TITLE
ACL for pdb-submitter

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#116]
`pdb-submitter` was able to bypass the entire workflow and move an entry to `HOLD`. 

`pdb-submitter` should only be allowed to choose from `DRAFT`, `DEPO`, and `SUBMIT` in https://data.pdb-dev.org/chaise/recordset/#1/Vocab:Workflow_Status@sort(Rank,RID).

**Comment by brindakv** [comment]
- Create a column in `Vocab:Workflow_Status` called `PDB_Submitter_Allow`. This column is boolean. 
- ACL update: If the column value is `true`, then the `pdb-submitter` can select the value. All values can be seen by the submitter. All values can be seen and selected by curators. 
- The values that should be set to `true` are: `DRAFT`, `DEPO`, and `SUBMIT`. All others are `false`.

**Comment by hongsudt** [comment]
@serban
Users should see all values in the Status, but they can only select a set
of values allowed. This list is not to control what they see, but what they
can select.

**Comment by brindakv** [comment]
@svoinea Agree with @hongsudt. `pdb-submitter` should be able to see `HOLD`, `REL`, and other workflow status. They should not be allowed to select terms other than `DRAFT`, `DEPO`, and `SUBMIT`.

**Comment by svoinea** [comment]
`pdb-submitter` is be able to see and **select** any value.

If he/she selects any other value than `DRAFT`, `DEPO` or `SUBMIT`, the following error should be displayed:

<img width="1853" alt="PDB_Forbidden" src="https://user-images.githubusercontent.com/1609577/208032580-12c2df23-d1dc-4f05-913a-d2db7b456508.png">

That will prevent saving it in the `ermrest` database.

Testing is available on catalog `99`.

**Comment by brindakv** [comment]
Looks good on catalog `99`. @hongsudt please confirm if this is the correct behavior.

**Comment by brindakv** [comment]
Looks good on production.
