### ISSUE TITLE
Accession code issued prematurely

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#118]
Some entries on production have accession codes issued prematurely. Eg: `D_2-J5KA`. 

This happened because of a bug in the code implemented on December 2nd, 2022. All entries with accession_serial instead of only entries with existing accession_code were assigned accession_code. 

Solution is to update ACL as follows: 

 - `pdb-submitter` can only see the `Accession_Code` when the `Workflow_Status` is set to `HOLD` or `REL`

 - Find entries on production that have `Accession_Code` issued but are not on `Workflow_Status` `HOLD` or `REL`
 
The snapshot to be used for 2022-12-02 at 16:00 pm (an hour before the migration happened) is: 2YX-R936-NC2E

Here is the URL: https://data.pdb-dev.org/chaise/recordset/#1@2YX-R936-NC2E/PDB:entry

14 entries after 2022-01 that have no accession_code assigned. 
https://data.pdb-dev.org/chaise/recordset/#1@2YX-R936-NC2E/PDB:entry/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM7i1ySQEsUIB9LFKPAGhCwAsUSi54I0AbbgXQC+dZOmx5YIACI4ADilIAXCpLAL6IDJADmOJB1ABbEhHwAmAAynTAWnMBGa1ZADBgoA@sort(RCT::desc::,RID)

**Comment by svoinea** [comment]
The ACL for the `Accession_Code` column of the `entry` table were defined such that:
 - the `Accession_Code` values are always visible to the `curators`
 - `submitters` can view only in the records they owned the `Accession_Code` values if `Workflow_Status` is `HOLD` or `REL`

The ACL were applied on development, staging and production.

**Comment by brindakv** [comment]
Unable to test this on `dev` because of #121.

**Comment by brindakv** [comment]
Looks good on `dev` and `staging`, but cannot test on production.

**Comment by brindakv** [comment]
Submitter confirmed that accession codes are not visible for an entry that is on workflow status `mmCIF Created`. Closing this issue.
