### ISSUE TITLE
Update description for Authors* and Authors in Citations*

### ISSUE THREAD

**Issue by monica81567** [informatics-isi-edu/protein-database#124]
Change Authors* description from "Authors of the structure; mmCIF category: audit_author" to "Authors of the structure; mmCIF category: audit_author Use format Lastname, F.M. eg. Vallat, B.V."

Changes Authors in Citations* from "Authors associated with publications in the citation list; mmCIF category: citation_author" to "Authors associated with publications in the citation list; mmCIF category: citation_author Use format Lastname, F.M. eg. Vallat, B.V."

Thanks.

**Comment by brindakv** [comment]
Change table comments in the following tables: 
 - `audit_author`: Authors of the structure; mmCIF category: audit_author; Example of author name format: Jones, T.J. 
 - `citation_author`: Authors associated with publications in the citation list; mmCIF category: citation_author; Example of author name format: Jones, T.J.

**Comment by svoinea** [comment]
The comment has been updated on catalog `99`.

**Comment by brindakv** [comment]
Looks good on `99`.

**Comment by svoinea** [comment]
The comment was already deployed on production.
