### ISSUE TITLE
entry.Release_Date should not be editable by pdb-submitter

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#126]
`entry.Release_Date` is currently editable by `pdb-submitter` (see `2-KRSW`). Looks like a bug that needs to be fixed.

**Comment by svoinea** [comment]
Issue fixed on catalog `99`.

**Comment by brindakv** [comment]
Looks good on catalog `99`.

**Comment by brindakv** [comment]
Check the policy: If `release_date` is assigned, it should not be changed by the backend script. `pdb-submitter` can only view but cannot edit it. `pdb-curator` can edit it at any time, but should be used cautiously.

**Comment by brindakv** [comment]
@svoinea confirmed the policy. Can now be deployed.

**Comment by brindakv** [comment]
Looks good on production.
