### ISSUE TITLE
create master ACL script

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#130]
The script has been created and deployed to dev. The script is in the pdb_dev python module e.g. pdb_dev.config.acl.ermrest_acl.py

It is ready for testing especially for pdb_submitters.

**Comment by brindakv** [comment]
Issues detected during testing on `dev`: 
 - After `Workflow_Status` reaches “mmCIF CREATED”, user does not have edit access but has “add” access to all tables. This does not happen on production. 
 - User is able to choose `Workflow_Status` options `RECORD READY` and `ERROR` from the `Entry_Related_File` table, which should not be allowed. This also happens on production (see #131). 
 - In the `Entry_Error_File` table, there is a bug in production, where the user is able to see data pertaining to entries created by others. This needs further testing on `dev`.

**Comment by brindakv** [comment]
There are some tables that are not visible to / editable by users / curators.
 - Curator non-editable tables
   - Sequences of Polymeric Entities (mmCIF category: entity_poly_seq)
   - Instances of Molecular Entities (mmCIF category: struct_asym)
   - Dictionary Versions Compliant with the Data (mmCIF category: audit_conform)
 - Users non-editable tables
   - Chemical Components (mmCIF category: chem_comp)
   - Polymeric Entities (mmCIF category: entity_poly)
   - Sequences of Polymeric Entities (mmCIF category: entity_poly_seq)
   - Types of Atoms (mmCIF category: atom_type)
   - Instances of Molecular Entities (mmCIF category: struct_asym)
   - Models Submitted (mmCIF category: ihm_model_list)
 - Tables not visible to user
   - Dictionary Versions Compliant with the Data (mmCIF category: audit_conform)

**Comment by brindakv** [comment]
Curators are unable to edit `audit_conform`, which is not set by the ACL policy. @svoinea to check annotations.

**Comment by svoinea** [comment]
I have checked and the `audit_conform` table has the annotation `tag:isrd.isi.edu,2016:generated`.

**Comment by brindakv** [comment]
Thanks, @svoinea. Does this [tag:isrd.isi.edu,2016:generated](https://docs.derivacloud.org/users-guide/annotations/annotation.html#tag-2016-generated) indicate that the table is generated by the system and is therefore not editable by admins or curators?

**Comment by hongsudt** [comment]
This annotation tells chaise to hide both create/edit buttons everywhere
regardless of user groups.

**Comment by brindakv** [comment]
@brindakv to review which tables have annotation: [tag:isrd.isi.edu,2016:generated](https://docs.derivacloud.org/users-guide/annotations/annotation.html#tag-2016-generated). 

Remove the generated annotation for `audit_conform`.

**Comment by brindakv** [comment]
The following tables / columns have the annotation `tag:isrd.isi.edu,2016:generated`.
- Vocab.id
- Vocab.uri
- PDB:entry.id
- PDB:Accession_Code
- PDB:audit_conform
- PDB:Conform_Dictionary
- PDB:entity_poly_seq
- PDB:struct_asym
- PDB:Entry_Error_File

**Comment by brindakv** [comment]
@brindakv to test which of the above table annotations can be removed. 

`Vocab.ID` and `Vocab.URI` can be made not visible to and not editable by anybody in the ACL (nothing needed in annotations). The values are set default by the system. All Vocab tables in PDB-Dev are locally defined.  

@svoinea to checked whether there are Vocab tables with columns id, uri, name, and description (lowercase column names). If not, we can clean up the corresponding annotations. 

PDB:entry.id: should be added to ACL.

**Comment by hongsudt** [comment]
- Vocab ID/URI/Owner columns: block all access (e.g. no access to definition and any operation) 
- PDB Owner column: block all access
- entry.id: block insert/edit/delete

**Comment by svoinea** [comment]
I have checked and none of the vocabulary tables has a column named lowercase `id`, `uri`, `name` or `description`.

**Comment by brindakv** [comment]
@brindakv to remove all references to id, uri, name or description in Vocab.

**Comment by brindakv** [comment]
Looks good on 99.
