### ISSUE TITLE
Entry_Error_File ACL

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#133]
In the `Entry_Error_File` table, there is a bug in production, where the user is able to see data pertaining to entries created by others. 

There is a different bug on `dev`, where the user is unable to see data pertaining to entries created by self in the same table.

**Comment by hongsudt** [comment]
Can you please tell me the entry rid on dev for debugging?

**Comment by brindakv** [comment]
The entry RID on dev is `2-M68E` belonging to user `isrdpdb test`.

**Comment by brindakv** [comment]
Fixed on both dev and production.
