### ISSUE TITLE
Release PDB-Dev structures to wwPDB FTP archive

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#138]
The released entries should be in https://files.wwpdb.org/pub/pdb/data/structures/. 

- Define sub-directory structure on wwPDB FTP server (Brinda and Jasmine)
- Discuss the API for file transfer (Zukang and PDB-Dev team)
- Develop script for file transfer
- Provide disk allocation numbers
  - list of files to archive: mmCIF, validation report, ???

**Comment by hongsudt** [comment]
statistics: 
- mmCIF:
  - avg file size:
  - max file size:
  - number of mmCIF: 
- validation report: 
  - avg file size
  - max file size
  - number of files

**Comment by hongsudt** [comment]
This issue has been replaced by #209. I am closing this.
