### ISSUE TITLE
Collision of output.cif filename uploaded as the input mmCIF file

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#141]
Issue created in python-ihm: https://github.com/ihmwg/python-ihm/issues/115

Until this is fixed, prepend the user uploaded mmCIF filename with entry `RID`.

**Comment by svoinea** [comment]
All the files that are provided as an input to the `make_mmCIF.py` utility are now prepended with the RID.

**Comment by brindakv** [comment]
@brindakv to test on dev.

**Comment by brindakv** [comment]
Looks good on catalog `99`.

**Comment by svoinea** [comment]
Right now, just the input file is prepended with the `RID`.

The output file is then moved into the `tests-validate/test-output/ihm-files/` directory where the `tests-validate/testSchemaDataPrepValidate-ihm.py` script is executed. It produces the `tests-validate/test-output/ihm-files/*.json` files which are then loaded into the `ermrest` database.

Therefore, just prepending the `RID` to the output file, does not prevent the `collisions` during a parallel processing.

Probably, everything should be done under a `RID` directory. Based on what I see in the `testSchemaDataPrepValidate-ihm.py` file, the script is using relative paths for the generated files. Therefore, it needs to be copied under the `RID` directory for each execution .

**Comment by hongsudt** [comment]
We have addressed this problem to avoid collision between the output file and input file. I am closing this issue and create a new one for pipeline improvement to support concurrent execution in issue #151.
