### ISSUE TITLE
Migrate dev to aws

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#147]
follow the same instruction in #146.

**Comment by svoinea** [comment]
Built the VM `dev-aws.pdb-dev`.
As of today, it has:
 - 4 CPU
 - 16G RAM
 - 50G hatrac space

It handles both dev (catalog `99`) and staging (catalog `50`).

**Comment by hongsudt** [comment]
dev is now on aws. I am closing this issue.
