### ISSUE TITLE
Create unique constraint for Entry: unique(RCB, mmCIF_File_MD5)

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#149]
We decided during the meeting on June 16 to not enforce any uniqueness on File MD5. This will not cause any issue in the new hatrac namespace, since each RCB store hatrac in its own namespace; so there should be no collision of same file content uploaded by different users. 

We decided to enforce unique constraint in Entry table for (RCB, mmCIF_File_MD5) to avoid users creating multiple entries for the same mmCIF file (less work for curators to deal with). 

The unique constraint can be dropped in the future without affecting hatrac acls.

**Comment by hongsudt** [comment]
@brindakv uses the same mmCIF file for testing on dev. This unique constraint will inconvenient the testing process. 

I don't think it is a good idea to apply different constraints between dev, staging, and production. So we will leave this out and let curators keep an eye on duplicates.

**Comment by brindakv** [comment]
Based on the discussion on Jan 9 2024, unique constraint in Entry table for (RCB, mmCIF_File_MD5) will be enforced on `dev`, `staging`, and `production`.
