### ISSUE TITLE
Error in "type" column in the Software table

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#15]
The column "type" in the software table is not correct. It doesn't match with the definitions and the set of controlled vocabularies in the JSON schema. The data doesn't match with the corresponding JSON files.

**Comment by brindakv** [comment]
Sorry, the "type" column is populated correctly in the software table. The only issue is why it has a foreign key reference, when there is none in the JSON schema.

**Comment by brindakv** [comment]
Same is true for "type" column in the Chem Comp table as well.

**Comment by svoinea** [comment]
In the `software` table, the `type` column is a foreign key to the `"Vocab".software_type_term("ID")`.

In the `chem_comp` table, the `type` column is a foreign key to the `"Vocab".chem_comp_type_term("ID")` table.

**Comment by hongsudt** [comment]
You will need to change the visible columns under `vocab/software_type.py` and/or `vocab/chem_comp_type.py`.
