### ISSUE TITLE
Last Communicated date is not working on production or dev

### ISSUE THREAD

**Issue by monica81567** [informatics-isi-edu/protein-database#152]
Added Last Communicated date by clicking today button (and also tried manually adding a previous date):

![image](https://github.com/informatics-isi-edu/protein-database/assets/103751282/a283088c-26b3-4039-a0f1-d50486cdf7aa)

and it does not get recorded.  I checked in the entry and it is now blank:
![image](https://github.com/informatics-isi-edu/protein-database/assets/103751282/957a478b-b833-4ac7-b57d-f25eea8a5a77)

And I checked in the table and the Last Communicated does not show a date.
![image](https://github.com/informatics-isi-edu/protein-database/assets/103751282/3c9af658-9941-4775-9f17-2dc1b84db147)

Looks like it was working back in April:
![image](https://github.com/informatics-isi-edu/protein-database/assets/103751282/5f6b4bcf-526c-477f-a7b7-39eaaec2b945)

And I am able to change that April date to today's date:
![image](https://github.com/informatics-isi-edu/protein-database/assets/103751282/d9e546df-7136-4724-a711-59563db64703)

**Comment by svoinea** [comment]
The requirement for the `Last Communicated Date` to be `NOT NULL` was only if the `Submitter Flag` is `true`.
The attached screenshots confirm it.
The implementation for this feature is done through a trigger.

**Comment by brindakv** [comment]
- Update annotations to show `Last Communicated` in entry recordset facets instead of `Submitter Flag Date`. 
 - Update comment for `entry.Submitter_Flag_Date`: Add the sentence "This date can only be set when Submitter_Flag" is `True`.

**Comment by svoinea** [comment]
I have applied the updates on `PDB DEV` (catalog `99` and `50`), `PDB PROD` (catalog `1`) and `PDB DEV AWS` (catalog `99` and `50`).

**Comment by monica81567** [comment]
I tried catalog 99 https://dev.pdb-dev.org/chaise/recordset/#99/PDB:entry@sort(RCT::desc::,RID) and still cannot add today's date or a previous date for test entry 2-Q4K2

**Comment by brindakv** [comment]
@svoinea Thanks.
