### ISSUE TITLE
Migrated hatrac namespaces for flask compability

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#155]
Prior to flask update, hatrac doesn't handle special characters properly e.g. it allows characters like ` ` or `/` to be in the path/dir names. The flask version address this issue which implies that after the update, the old objects will not be reachable until we rename them appropriately.  Note: renaming hatrac paths and files while using the non-flask versions, will cause these files to be unreachable.  

This issue is addressed in s3 object storage, but not the file system block storage.

@svoinea found 40+ entries that have this problem, all of them are not referred to in live ermrest (though they are likely referred to in older snapshots)

To address this issue, we should try to do the update and renaming shortly after. I would do the following: 
- [ ] update the server
- [ ] right before the actual renaming, backup everything, in case something go wrong, we can recover and restart
- [ ] rename those objects R.   
- [ ] check the flask/python version to avoid 404 issue when path names are too long. 
- [ ] update software if needed. 

@karlcz has a script prepared that we can use. So we should review the script, test it, and then deploy it. 
@svoinea please ask karl where we can find the script.

**Comment by svoinea** [comment]
Identified the `hatrac` rows by running the query:
```
SELECT name FROM name WHERE name ~ '[^-_.~A-Za-z0-9/]';
```
Updated the hatrac DB names by `urlquote` them.
Updated the hatrac files system by renaming the files names with the `urlquote` of them.
