### ISSUE TITLE
Missing entry images from users

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#158]
- Update tool tip with the text: 
   - Image provided will be used for the entry on the PDB-Dev website (BV)
 - Create a default image for missing images (MRS)
   - Warning: Image not provided
 - Upload default image to hatrac with public permission (Serban)
   - /pdb/public/images/missing_image.png
 - Add at trigger to use the default missing image (Serban)

**Comment by monica81567** [comment]
![](https://files.slack.com/files-pri/T1UGYNTNC-F05SS7GF7F1/no_image_uploaded.jpg)

**Comment by svoinea** [comment]
Image with 150 x 150 pixels:

![missing_image](https://github.com/informatics-isi-edu/protein-database/assets/1609577/edb85e4a-8833-440a-a4e3-980ed5892a54)

**Comment by monica81567** [comment]
Thank you!

**Comment by svoinea** [comment]
The image was loaded on `hatrac` and the trigger was defined on both dev ISI and dev AWS VMs for both catalogs `99` and `50`.

**Comment by monica81567** [comment]
Works as expected on aws dev.  Thanks Serban!

**Comment by brindakv** [comment]
Waiting on policy review for access control.

**Comment by brindakv** [comment]
@monica81567 Please check the tooltip updated on `dev`.

**Comment by monica81567** [comment]
Tested fine on dev

**Comment by brindakv** [comment]
Still needs to be deployed on production.

**Comment by monica81567** [comment]
Got it.  I won't close until it gets to production?  Or you are in charge of closing tickets? @brindakv

**Comment by brindakv** [comment]
Yes, I will close it once deployed.

**Comment by brindakv** [comment]
Tooltip updated on production. Waiting on policy review for access control .
