### ISSUE TITLE
Add tooltip info for mmCIF file for starting model

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#159]
This should indicate `The chain identifiers and residue numbers in these mmCIF files should match the data entered into the table.  PDB file format can be converted to mmCIF using MAXIT or https://mmcif.pdbj.org/converter/index.php?l=en`. 

Consider adding the above text to table comment.

**Comment by brindakv** [comment]
@monica81567 Please check the tooltip updated on `dev`. Please note that the update is at the column level and not the table level.

**Comment by monica81567** [comment]
@brindakv Again the wording is different from the proposed wording.  It starts with URL of the uploaded starting model mmCIF file.  Is this a bug?  The rest is fine.

**Comment by monica81567** [comment]
Tested fine on dev

**Comment by brindakv** [comment]
Still needs to be deployed on production.

**Comment by brindakv** [comment]
Deployed on production.
