### ISSUE TITLE
Multiple Visible Foreign Keys in the Entity Poly Seq Table

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#16]
The "ihm_entity_poly_segment" table has multiple pointers to the "entity_poly_seq" table, which has a composite key. The visible foreign keys in the "entity_poly_seq" table, display multiple link to "ihm_entity_poly_segment" table. I am not sure if this is required and if removing the duplicate foreign keys will have any effect in the tables shown.

**Comment by svoinea** [comment]
The `ihm_entity_poly_segment` table has just two composite foreign keys to the `entity_poly_seq` table:
```
"ihm_entity_poly_segment_mm_poly_res_label_begin_fkey" FOREIGN KEY (structure_id, seq_id_begin, comp_id_begin, entity_id) REFERENCES entity_poly_seq(structure_id, num, mon_id, entity_id) ON UPDATE CASCADE ON DELETE SET NULL

"ihm_entity_poly_segment_mm_poly_res_label_end_fkey" FOREIGN KEY (entity_id, seq_id_end, structure_id, comp_id_end) REFERENCES entity_poly_seq(entity_id, num, structure_id, mon_id) ON UPDATE CASCADE ON DELETE SET NULL
```
And the `entity_poly_seq` table has just the two references from those keys.

The two composite foreign keys are not a duplicate one to the other. The difference comes from `seq_id_begin, comp_id_begin` vs. `seq_id_end, comp_id_end`, i.e. one marks the `begin` of a sequence, while the other marks the `end` of the sequence.

Go to the https://pdb.isrd.isi.edu/chaise/recordset/#1/PDB:entity_poly_seq@sort(RID) link.
You will see in the facets filter two foreign keys named `Ihm Entity Poly Segment`, but they are different.
Select from the first one the value `1`. You will get 
![Screenshot-1](https://user-images.githubusercontent.com/1609577/70195906-e3841100-16bb-11ea-818c-b46b4a5f4919.png)
Deselect the `1` value and select the `1` value from the second one. You will get 
![Screenshot-2](https://user-images.githubusercontent.com/1609577/70196047-48d80200-16bc-11ea-857c-9d890c320937.png)

As you can see they are different as they are coming from different references.

**Comment by svoinea** [comment]
The "duplicate" problem is now fixed by defining the `from_name` foreign key annotation.
Example of how a foreign key annotation looks now:
```
    em.ForeignKey.define(
        ['comp_id_begin', 'seq_id_begin', 'entity_id', 'structure_id'],
        'PDB',
        'entity_poly_seq', ['mon_id', 'num', 'entity_id', 'structure_id'],
        constraint_names=[['PDB', 'ihm_entity_poly_segment_mm_poly_res_label_begin_fkey']],
        annotations={
            chaise_tags.foreign_key: {
                'from_name': 'Ihm Entity Poly Segment Begin',
                'template_engine': 'handlebars',
                'domain_filter_pattern': '{{#if _structure_id}}structure_id={{{_structure_id}}}{{/if}}'
            }
        },
        acls={
            'insert': ['*'],
            'update': ['*']
        },
        on_update='CASCADE',
        on_delete='SET NULL',
    ),
 ```
This how the filter panel looks now: 
![Screenshot-3](https://user-images.githubusercontent.com/1609577/70288552-e0098c00-1786-11ea-8544-d07ef1531548.png)
and how the detail page looks now:
![Screenshot-4](https://user-images.githubusercontent.com/1609577/70288676-2eb72600-1787-11ea-9c6e-b8506c60a8f8.png)

The annotation was defined on the following tables:
```
ihm_entity_poly_segment
ihm_cross_link_list
ihm_cross_link_restraint
ihm_predicted_contact_restraint
ihm_poly_residue_feature
ihm_residues_not_modeled
```

**Comment by svoinea** [comment]
The issue was fixed.
