### ISSUE TITLE
Do not allow users to upload PyMOL files

### ISSUE THREAD

**Issue by monica81567** [informatics-isi-edu/protein-database#161]
Can the file upload check the first line of the cif file and block files that have first line:
# generated by PyMOL 2.5.5

or 
# generated by PyMOL

Two users uploaded PyMOL files within the past week.  It would be great if we could block these,

Create new entry page, next to "User Provided mmCIF File" we could add wording like "Do not upload files generated by PyMOL" or we could add it to the info pop-up along with "We recommend that you use MAXIT https://sw-tools.rcsb.org/apps/MAXIT/index.html or https://mmcif.pdbj.org/converter/index.php?l=en to convert PDB to mmCIF format.  

![image](https://github.com/informatics-isi-edu/protein-database/assets/103751282/8dbb5d64-9109-4a33-a9a3-e4f4f0640b78)

**Comment by brindakv** [comment]
Update tooltip text: Use MAXIT or python-ihm to convert PDB to mmCIF. Using other tools may not create compliant files.

**Comment by brindakv** [comment]
@monica81567 Please check the tooltip updated on `dev`.

**Comment by monica81567** [comment]
Tested fine on dev.

**Comment by brindakv** [comment]
Still needs to be deployed on production.

**Comment by brindakv** [comment]
Deployed on production.
