### ISSUE TITLE
Release dates not showing

### ISSUE THREAD

**Issue by monica81567** [informatics-isi-edu/protein-database#165]
Entries that are being released today show the release dates, but past releases do not show the release date.

![image](https://github.com/informatics-isi-edu/protein-database/assets/103751282/8a78122b-2e56-4f44-b4ad-7cb22130784e)

**Comment by svoinea** [comment]
I have checked and the `Release_Date` is set to the current date ONLY if it was NOT already set and you changed the `Workflow_Status` to `SUBMISSION_COMPLETE`.

**Comment by brindakv** [comment]
Related to #191

**Comment by brindakv** [comment]
@monica81567 Can you please test if this issue is resolved on `dev`?

**Comment by monica81567** [comment]
I don't think this is working on dev.  There are 23 entries with REL status, but only 13 entries with release dates.

**Comment by brindakv** [comment]
@monica81567 If the entries were released before the workflow was updated to assign and populate release dates, they will not show release dates. 

Could you check the metadata in the mmcif files for some some these entries with missing release dates to see if they were released before `Sep 10, 2022` when #85 was closed?

**Comment by monica81567** [comment]
@brindakv I spot checked a few of them and they are all before September 10, 2022.
