### ISSUE TITLE
Test processing pipeline on RCSB cloud ubuntu instance

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#167]

**Comment by svoinea** [comment]
The processing pipeline was tested on the Ubuntu instance `128.6.158.51` for all the workflow status.
It worked.

Based on the current status of the instance, it required the installation of the `g++` library, which at its turn required adding the `ppa:ubuntu-toolchain-r/test` repository.

The `g++` library was required by the `CifCheck` process.

**Comment by brindakv** [comment]
@svoinea Can I close this issue?

**Comment by hongsudt** [comment]
I am closing this issue since we already have a pipeline running on ubuntu.
