### ISSUE TITLE
Model updates for validation reports

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#169]
Ermrest model updates to handle validation reports (completed on `dev`)
 
1. `Validation_File_Type` (used by `Entry_Error_File`) 
  - [x] Rename  to `System_Generated_File_Type`
  - [x] Update all references and annotations
  - [x] Update definitions of existing terms to be consistent
  - [x] Add/update vocabulary terms (following naming convention and add description)
   - mmCIF
   - JSON
   - Log: CifCheck diagnostic error file
   - Log: CifCheck parser error file
   - Validation Report: Full PDF
   - Validation Report: Summary PDF
   - Validation Report: HTML tar.gz
2. Entry_mmCIF_File
  - [x] Rename to `Entry_Generated_File`
  - [x] Update all references and annotations
3. Entry_Generated_File
 - [x] Update display name from `System generated mmCIF file` to `System generated file`
 - [x] Add column `File_Type` and add fkey to `System_Generated_File_Type`
 - [x] Add/modify annotations
 - [x] Make sure `Conform_Dictionary` only applies to `File_Type` = `mmCIF`; @svoinea to confirm 
 - [x] Figure out how links to multiple system generated files can be provided from the compact view of `entry` table
 - [x] Change the unique constraint from (`Structure_Id`, `mmCIF_schema_version`) to (`Structure_Id`, `File_Type`)

Should `File_Type` be part of a composite key for `Entry_Generated_File`? YES

**Comment by svoinea** [comment]
I think `Yes`. I am not sure if a `UNIQUE CONSTRAINT` can have one of its column (in our case `mmCIF_Schema_Version`) set to `NULL`.

I think the current `PK`: 
```
"Entry_Generated_File_Structure_Id_mmCIF_Schema_Version_key" UNIQUE CONSTRAINT, btree ("Structure_Id", "mmCIF_Schema_Version")
```
should be replaced with something like:
```
UNIQUE CONSTRAINT, btree ("Structure_Id", "mmCIF_Schema_Version", "File_Type")
```

**Comment by svoinea** [comment]
On catalog `99`, in the `Entry_Generated_File` table, I have replaced the UNIQUE CONSTRAINT `(Structure_Id, mmCIF_Schema_Version)` by the  UNIQUE CONSTRAINT `(Structure_Id', File_Type)`.

I have also updated the https://github.com/informatics-isi-edu/protein-database/blob/master/config-scripts/schema-updates/validation_files/2023_01_Entry_mmCIF_File.py script in this respect.

**Comment by brindakv** [comment]
Model updates look good on `dev`. 

Cannot test the  `UNIQUE CONSTRAINT (Structure_Id, File_Type)` in the `Entry_Generated_File` table because creating new records manually is disabled for this table.

**Comment by brindakv** [comment]
@brindakv to check the unique restraint using the rest API schema.

**Comment by brindakv** [comment]
`UNIQUE CONSTRAINT (Structure_Id, File_Type`) in the `Entry_Generated_File` table exists. 

However, `File_URL`, `File_Name`, `File_MD5`, and `File_Bytes` in `Entry_Generated_File` are all set to `nullok = true` (see attached screenshot 1). However, chaise does not allow `File_URL` to be empty (see attached screenshot 2). 

![Image](https://github.com/informatics-isi-edu/protein-database/assets/15000874/69a45bc1-3205-4f08-bf01-8303a684fc83)

![Image](https://github.com/informatics-isi-edu/protein-database/assets/15000874/87da93ef-bb6d-4eaf-880b-665ec4bccf8b)

**Comment by brindakv** [comment]
Deployed on production.
