### ISSUE TITLE
ACL updates for validation reports

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#170]
ACL updates

- [ ] After renaming `Entry_mmCIF_File` → `Entry_Generated_File`, update ACL
- [ ] Validation: HTML tar.gz file in `Entry_Generated_File` should not be visible to user

**Comment by svoinea** [comment]
The ACLs were updated and applied on catalog `99`.
Submitter can see only the following System Generated Files:
 - *.cif
 - *_summary_validation.pdf
 - *_full_validation.pdf

**Comment by brindakv** [comment]
ACL for the system generated files look good on `dev`. However, there is another problem related to ACL. 

When a new user creates the first entry, there is a delay in accessing system generated files because the script that sets the ACL for the corresponding hatrac namespace runs hourly. 

The hatrac namespace is created by the backend user when the entry reaches the workflow status `mmCIF Created`, which is the first time when a system generated file is created for the entry. The ownership for this namespace is then subsequently assigned to the user when the hourly ACL script runs next. Until this happens, the user cannot access any of the system generated files. It is inconvenient to users when they see the system generated mmCIF file but cannot access it. Furthermore, they may not realize that they will be able to access it in an hour or so. 

One way to address this is to create the `generated` hatrac namespace when the workflow status `DEPO` is triggered so that the delay is not perceived by the user. There is a very good chance that the ACL script would have re-assigned the ownership of the `generated` namespace by the time the user completes the required workflow tasks to reach the `mmCIF Created` status.

**Comment by brindakv** [comment]
The ACL will handled separately.

**Comment by brindakv** [comment]
Looks good on staging.
