### ISSUE TITLE
Support for new entry collection deposition

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#177]
User wants to submit 130 new entries as part of a collection. 

Need a script to automate bulk deposition of compliant files. 

Suggestion: 

Use the Hatrac API to upload the files, get the URI, and then update Ermrest accordingly (see [here](https://github.com/informatics-isi-edu/protein-database/blob/master/scripts/pdb_processing/worker/pdb/clientlib/pdb_workflow_processing_lib/client.py)).

**Comment by brindakv** [comment]
- Add a natural unique constraint in the `entry` table - combination of user id and mmcif filename.

**Comment by svoinea** [comment]
Added on catalog `99` the constraint:
```
    "entry_RCB_mmCIF_File_Name_key" UNIQUE CONSTRAINT, btree ("RCB", "mmCIF_File_Name")
```
On catalog `1`, there are the following collisions:
```
                             RCB                              | mmCIF_File_Name | count 
--------------------------------------------------------------+-----------------+-------
 https://auth.globus.org/f9653733-1200-4259-9269-77d5101fe71e | npc_all.ihm     |     2
 https://auth.globus.org/cc42b37b-27fd-44ce-b027-ee8e6fc4b36f | model.cif       |     2
(2 rows)
```
where `https://auth.globus.org/cc42b37b-27fd-44ce-b027-ee8e6fc4b36f ` is `Kolja Stahl` and 
`https://auth.globus.org/f9653733-1200-4259-9269-77d5101fe71e` is `Jeremy Tempkin`.

**Comment by brindakv** [comment]
Use RID to remove collision.

**Comment by svoinea** [comment]
Fixed the collision also on production and created the constraint:
```
"entry_RCB_mmCIF_File_Name_key" UNIQUE CONSTRAINT, btree ("RCB", "mmCIF_File_Name")
```

**Comment by brindakv** [comment]
Thanks @svoinea. Closing this issue.
