### ISSUE TITLE
create new instance for workflow processing (production)

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#179]
- server name: workflow.pdb-dev.org 
- target date: Feb 5
- spec:
  - scratch space: 100GB
  - `/`: 50GB (including /home)
  - CPUs: 6
  - Memory: 32G
- backup: We will run our own rsync to back up to the RCSB staging backup server
- Notes: 
  - currently on dev: 
  - 100 GB scratch
  - 25 GB for root, of which 90% is used (22GB)

**Comment by svoinea** [comment]
`df` output:
```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G  968K  3.2G   1% /run
/dev/vda5        25G   22G  2.6G  90% /
tmpfs            16G     0   16G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
tmpfs           3.2G     0  3.2G   0% /run/user/1000
/dev/vdc1       100G   22G   79G  22% /mnt/vdb1
overlay          25G   22G  2.6G  90% /var/lib/docker/overlay2/ba50146613b8d8bb49fb10270bcdb75756c75e3008f8a6e6217d01e064bf60a1/merged
```
The `singularity` work directory is on `/mnt/vdb1`.

A snapshot  of the `du` where `singularity` was running last time:
```
# du -h -d1 /mnt/vdb1/dev_pdbihm
12M	/mnt/vdb1/dev_pdbihm/output
99M	/mnt/vdb1/dev_pdbihm/cache
65M	/mnt/vdb1/dev_pdbihm/input
21M	/mnt/vdb1/dev_pdbihm/IHMValidation_2.0_20231130
448M	/mnt/vdb1/dev_pdbihm/IHMValidation_2.0_20231222
9.3G	/mnt/vdb1/dev_pdbihm
```
A snapshot  of the `du` of the `/` directory:
```
# du -h -d1 /
4.6M	/etc
0	/media
149M	/boot
0	/dev
3.6G	/home
21G	/mnt
0	/opt
0	/proc
62M	/root
968K	/run
0	/srv
0	/sys
2.7G	/tmp
3.4G	/usr
19G	/var
170M	/SysAdmin
50G	/
```
A snapshot  of the `du` of the `/home` directory:
```
# du -h -d1 /home
1.7G	/home/ubuntu
12K	/home/con
20K	/home/radmin
1.9G	/home/pdbihm
109M	/home/isrddev
3.6G	/home
```
The size of the `singularity` binary:
```
# ls -l /usr/bin/singularity
-rwxr-xr-x 1 root root 38054880 Nov  9  2021 /usr/bin/singularity
```
Therefore:
 - the `pdbihm` user is the owner `/mnt/vdb1/dev_pdbihm` directory (the workspace of the `singularity`)
 - the volume of the `singularity` workspace is `/mnt/vdb1 100G`  from which currently only `22G` are used 
 - the home directory of the `pdbihm` user is `NOT` used for the `singularity` processing
 - the `docker` has also a volume allocated `overlay` of `25G` from which currently `22G` are used

**Comment by svoinea** [comment]
[singularity.txt](https://github.com/informatics-isi-edu/protein-database/files/14078602/singularity.txt)

Attached is a snapshot taken from the `top` command during the execution of the `singularity` tool:
```
top -1  -u pdbihm -b > top.txt
grep "top\|Tasks\|%Cpu\|MiB" top.txt > singularity.txt
```
