### ISSUE TITLE
Expand entry table to collect information regarding data used in integrative modeling

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#181]
Add a column to the entry table, `_entry.ihm_details`, to collect information from the depositor regarding the kinds of data/information/methodology used in integrative modeling during file upload. 

Add appropriate information in the tooltip. 

If the field is mandatory, update annotations for upload CLI to take a default value.

**Comment by monica81567** [comment]
Tooltip - How's this?  Too long?  I'm trying to be complete to minimize the back and forth with depositor.  

PDB-Dev is a repository for integrative structure models built by combining data from multiple experimental and/or computational methods.  Please provide specific information, types of data, and the methodology used in the modeling process.

**Comment by brindakv** [comment]
Thanks @monica81567.

**Comment by brindakv** [comment]
@monica81567 Please check on `dev`. It currently shows a `default` value for `entry.Method_Details`. This will be removed after deploying on production.

**Comment by monica81567** [comment]
Yes, I see "Integrative modeling".  So production won't show this "Integrative modeling"?  @brindakv Why are dev and production different?

**Comment by brindakv** [comment]
It has not been deployed on `production` yet. 

Both `dev` and `production` settings will be changed after the default values are set for existing entries. Because the data item is mandatory, we need a default value to begin with.

**Comment by brindakv** [comment]
Yes, existing entries will be remediated to have the term "Integrative modeling". 

New entries will have an empty box, which is mandatory. So users cannot proceed without filling it out. 

If we provide "Integrative modeling" by default for new entries, then the whole purpose of adding this data item is not served.

**Comment by brindakv** [comment]
This does not work with bulk upload even with updated annotations.

**Comment by brindakv** [comment]
Fixed by applying annotations at the catalog level instead of the schema level.

**Comment by brindakv** [comment]
Deployed on production.
