### ISSUE TITLE
BDBag export fails

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#187]
Using `BDBag` to export multiple system generated mmCIF files for a collection of entries fails. 
![Screenshot 2024-02-05 at 6 19 24 PM](https://github.com/informatics-isi-edu/protein-database/assets/15000874/7280a262-3304-40ea-8bae-17a352fe5a1a)

**Comment by brindakv** [comment]
@svoinea to update the details of the bug and the fix.

**Comment by svoinea** [comment]
The line that needed to be updated was in the `/etc/httpd/conf.d/wsgi_deriva.conf` file:

```
WSGIScriptAlias /deriva /usr/local/lib/python3.11/site-packages/deriva/web/deriva.wsgi
```
This file is generated by the `derivaweb_deploy` function which on `dev` is executed daily.
On production it had to be done manually, as it does not receive daily updates.

**Comment by brindakv** [comment]
Thanks @svoinea. 

How did this work on production before we moved to aws?

**Comment by brindakv** [comment]
How are the config files handled during deployment? @svoinea to check the deployment script.

**Comment by brindakv** [comment]
It is not clear what caused the issue in the first place. Closing it for now.
