### ISSUE TITLE
Manual issue of accession code

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#189]
Depositor wants accession code 536 for a particular entry on production: https://data.pdb-dev.org/chaise/record/#1/PDB:entry/RID=2-XFN2
```
insert into "PDB"."Accession_Code" ("Accession_Serial", "Entry") values(536, '2-XFN2');
update "PDB".entry set "Accession_Code" = (select "Accession_Code" from "PDB"."Accession_Code" where "Accession_Serial" = 536) where "RID" = '2-XFN2';
```

**Comment by svoinea** [comment]
The `Accession_Code` was already generated.

**Comment by brindakv** [comment]
Verified, looks good. Entry is now on `HOLD` and will be released soon.
