### ISSUE TITLE
Table comment tool tip is not visible in related tables

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#19]
The `table comment` tool tip is not visible in related tables shown as visible foreign keys. For example, in the `entry` table view, the `table comment` for the related `citation` table is not visible. It is, however, visible in the detailed `citation` table view.

**Comment by hongsudt** [comment]
This is a known bug in Chaise which will be fixed in the next 1 month. @svoinea please keep an eye on chaise feature announcement. Once it is released, please inform @brindakv to review,.

**Comment by hongsudt** [comment]
@svoinea can you please check whether this issue has been resolved? If so, please close the issue.
