### ISSUE TITLE
Fix when `entry.Release_Date` is set

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#191]
`entry.Release_Date` has to be set when `Workflow_Status` is updated from `HOLD`--> `Release Ready` --> `REL`. 

Same is true for `_pdbx_audit_revision_history.revision_date` in the system generated mmCIF file, which has to match `entry.Release_Date`. 

`entry.Release_Date` is current being set when `Accession_Code` is issued i.e., when `Workflow_Status` is updated from `mmCIF Created`--> `Submission Complete` --> `HOLD`.

**Comment by svoinea** [comment]
Problem was fixed and deployed on catalog `99`.

**Comment by brindakv** [comment]
See #182 for details about the workflow steps.

**Comment by brindakv** [comment]
Looks good on `dev`.

**Comment by brindakv** [comment]
@svoinea Has this been deployed on production?

**Comment by svoinea** [comment]
Yes.
