### ISSUE TITLE
Regenerate validation reports for released entries

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#192]
Before deployment of the new workflow for generating validation reports (see #163, #169, #170, #171), validation reports for already [released entries](https://pdb-dev.wwpdb.org/solrsearch.html?query=*:*) need to regenerated and made publicly available on the [PDB-Dev](https://pdb-dev.wwpdb.org/index.html) website. 

Because the new workflow has updated file names and file organization consistent with wwPDB practices, the validation report regenration has to coordinated with the deployment of the new workflow. 

The validation reports also need to be uploaded to the [deposition system](https://data.pdb-dev.org/) for all released entries.

**Comment by aozalevsky** [comment]
@brindakv Since it's now technically possible to regenerate all the reports offline, we need an actual mechanism to populate them. Which host should I use (dev, production?), and where do you want me to put files so you can integrate them into the system?

**Comment by brindakv** [comment]
@aozalevsky Please use `dev` to regenerate the validation reports. `production` will be rebuilt soon. 

Please put the files on `dev` under `/mnt/vdb1/Validation_v1.1`.

**Comment by aozalevsky** [comment]
@brindakv just to clarify, did you test/do you approve the current version of the pipeline on dev? Can I tag it and pass it to @svoinea for production?

**Comment by brindakv** [comment]
@aozalevsky Yes, I tested the current version of the validation code on dev. It can be tagged for production.

**Comment by aozalevsky** [comment]
@brindakv all reports are ready on `dev` instance at `/mnt/vdb1/Validation_v1.1/`
