### ISSUE TITLE
Provide "description" for foreign key items

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#2]
The item description for foreign key items can be derived from the parents and shown while hovering. If that turns out to be difficult, we can update the JSON schema to include this information.

**Comment by hongsudt** [comment]
- Prepend column type to the comment. 
- Use the Item description as Comment when exists.  Example of column with the item description.
http://mmcif.wwpdb.org/dictionaries/mmcif_ihm.dic/Items/_ihm_entity_poly_segment.comp_id_begin.html

**Comment by svoinea** [comment]
For the example above, the provided `json` file for the schema definition does not contain the `description` key:
```
      "ihm_entity_poly_segment": {
         "type": "array",
         "items": {
            "type": "object",
            "properties": {
               "structure_id": {
                  "$ref": "#entry/id",
                  "_primary_key": true
               },
               "comp_id_begin": {
                  "$ref": "#entity_poly_seq/mon_id",
                  "_attribute_groups": [
                     {
                        "id": "mm_poly_res_label",
                        "label": "mm_poly_res_label_begin"
                     }
                  ]
               },
```
Therefore, the description was inherited from the parent table.
