### ISSUE TITLE
Create a weekly update manifest

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#204]
- Location of the file
 - Content @brindakv find what the timestamp corresponds to, if it is a stable release timestamp, and how updates are tracked
    - Example: https://files.wwpdb.org/pub/pdb/holdings/released_structures_last_modified_dates.json.gz
    - Timestamp corresponds to the latest modified time (information from Jasmine)

**Comment by hongsudt** [comment]
Will close (duplicate with #209) . #209 has all the outline plan.
