### ISSUE TITLE
Set up access control

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#21]
Create the following globus groups to integrate access control. Please make brinda the group admin, so she can manage all those
- pdb-submitter: data submitters
- pdb-curator: brinda
- pdb-admin: owner ---> brinda, isrd-staff

  - write: 
    - can only create ENTRY; 
    - can delete/update before SUMBIT. 
    - no update/delete after SUBMIT

  - read: 
   - Can read own entries for all workflow status.  

ERMrest ACL:
- pdb-submitter: ENTRY 
  - [x] should not see entries created / owned by other users
  - [x] can create an ENTRY
  - [x] can update/delete own ENTRY records before SUBMIT (i.e., DRAFT, DEPO, RECORD READY, and ERROR)
    - Clean up the vocab table cascading problem
    - Don't want them to re-upload files after DEPO--->write triggers to check that this doesn't happen
    - Note: Issue with ermrest: If a record is in the allowed list, submitters can change the status to any value in the fk list. --> **Karl suggested solving this problem through trigger** 
  - [ ] can only see DRAFT, DEPO, and SUBMIT status in the workflow status drop down list -- Not solvable as it ties to what shows up on the recordset page
  - [x] can have read access to all own ENTRY records regardless of Workflow status---as long as their own the records, they can read (with or without the Workflow status)

- pdb-submitters: populated tables (step 2) 
  - [x] No write access to specific tables in any state of the workflow (for list of non-editable tables please check the [data submission workflow](https://github.com/informatics-isi-edu/protein-database/wiki/data-submission-workflow) wiki page
  - [x] Other tables (listed as editable in the [data submission workflow](https://github.com/informatics-isi-edu/protein-database/wiki/data-submission-workflow) wiki page) can be edited using the frontend before SUBMIT
  - [x] can have read access to all own ENTRY records regardless of Workflow status---as long as their own the records, they can read (with or without the Workflow status)

- pdb-submitters: all tables that point to ENTRY (steps 3/4). Check google slides / [data submission workflow](https://github.com/informatics-isi-edu/protein-database/wiki/data-submission-workflow) wiki page for list of tables. 
  - [x] can create rows in those tables before SUBMIT. (In practice, this need to wait until corresponding ENTRY is RECORD_READY through documentation)
  - [ ] can only see DRAFT, DEPO, and SUBMIT status in the workflow status drop down list.
  - [x] can have read access to all own ENTRY records regardless of Workflow status---as long as their own the records, they can read (with or without the Workflow status)

- pdb-submitters: Entry_Related_Files 
  - [x] can update/delete own records before SUBMIT. 
  - [x] can update/delete own ENTRY records before SUBMIT. 
    - Don't want them to re-upload files after DEPO--->write triggers to check that this doesn't happen (this is for consistency with step 2 even though there is no dependency on populated tables in 4)
    - How to trigger the script: @svoinea suggested on error, change the Workflow to Draft, users fix others issues in step 2/3, change Workflow to DEPO to trigger processing. Another option is to have an ERROR status that capture this case specifically. 

- [x] pdb-curator: can create, update, read any entries
- [x] pdb-admin (+ isrd_staff): can change model and have access to everything
- [ ] Future policy: Submitters can read any records with "REL" status -- Need to verify with PDB

Hatrac ACL:
- [ ] pdb-submitter can only create files; no deletion or update. Can only read its files. At present. the owner of the file can delete but not update. **To enforce no deletion, ownership has to be changed at some point during the workflow (when?)**. This will be reviewed later. 
- [x] pdb-curator: can create, update, read any files
  - Note: @svoinea will test the deletion through curl/deriva-py. @brindakv test the read/re-upload through chaise
- [x] pdb-admin (+ isrd_staff): can create, update, read any files
  - Note: @svoinea will test the deletion through curl/deriva-py. @brindakv test the read/re-upload through chaise

The following `hatrac` ACL were defined:
```
 - subtree-create for [pdb_admin, pdb_curator, pdb_submitter]
 - subtree-update for [pdb_admin, pdb_curator]  --> Does this include Delete? 
 - subtree-read for [pdb_admin, pdb_curator, pdb_submitter]
```

The google slide has detail: https://docs.google.com/presentation/d/13x0-6285zmdRYer0Sc2R223kfntFOvh0/edit#slide=id.p1

**Comment by svoinea** [comment]
The group `pdb-curator` already exists.
I have created the `pdb-user` group.

**Comment by svoinea** [comment]
Added Brinda as administrator of the `pub-user` group.
That will allow her to add/remove members of the group.

**Comment by hongsudt** [comment]
@svoinea can you check whether there are other groups that we had created for pdb?

**Comment by svoinea** [comment]
I have renamed the group `pdb-user` to `pdb-submitter`.

**Comment by svoinea** [comment]
I have defined on catalog `99` the `ACL` for the `entry` table as well as for the tables referencing it.

**Comment by hongsudt** [comment]
@brindakv please review

**Comment by brindakv** [comment]
I created a new globus account, added it to `pdb-submitter` group, added row to the `Entry` table in catalog 99 as new user and uploaded a file. After file upload, I get a `Record Not Found` error. Perhaps, the `pdb-submitter` group does not have the correct access.

**Comment by brindakv** [comment]
After @svoinea updated access control for the `Entry` table, user with `pdb-submitter` permissions can see the `Entry` table. However, `pdb-submitter` can also see entries created by @svoinea.

**Comment by brindakv** [comment]
@svoinea please check the [data submission workflow](https://github.com/informatics-isi-edu/protein-database/wiki/data-submission-workflow) wiki page for the list of tables auto-populated in step 2 that should not be editable via the frontend.

**Comment by brindakv** [comment]
Access control issues for `pdb-submitter`

 - `Entry` table `workflow_status` shows `Record Ready` but none of the tables from step 2 are shown.
 - Step 3 manual entry tables (e.g., audit_author) show error while creating rows.

**Comment by svoinea** [comment]
There were a number of `15` tables that did not not belong to step `2`, `3` or `4` and did not have `acl` defined:
```
    "chem_comp_atom",
    "citation_author",
    "pdbx_inhibitor_info",
    "entity_src_gen",
    "entity_name_com",
    "software",
    "pdbx_entity_poly_na_type",
    "pdbx_ion_info",
    "audit_conform",
    "pdbx_entry_details",
    "audit_author",
    "citation",
    "entity_name_sys",
    "pdbx_protein_info",
    "pdbx_entity_nonpoly"
```
I have defined them.
I have also defined the `acl` for the vocabulary tables.
I have checked the second and third checkboxes from the above comment.

**Comment by svoinea** [comment]
The issue related to `User is able to see entries created by other users` was fixed.
