### ISSUE TITLE
Update IHM validation to v1.2

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#211]
IHMValidation v1.2 should address the availability remediated IHMCIF files that contain PDB accession codes along with PDB-Dev accession codes. 

Updated code should be incorporated into the pipeline and updated validation reports should be generated for all released entries.

**Comment by aozalevsky** [comment]
@brindakv, is there a `python-ihm` or `ihm dictionary` issue so I can keep track of when the data and code will be available?

**Comment by aozalevsky** [comment]
ok, it seems it was already implemented in https://github.com/ihmwg/python-ihm/issues/135

**Comment by aozalevsky** [comment]
@brindakv, here is an example output. Does it look reasonable?

[pdb_00009a2h_full_validation.pdf](https://github.com/informatics-isi-edu/protein-database/files/15275342/pdb_00009a2h_full_validation.pdf)
[pdb_00009a2h_summary_validation.pdf](https://github.com/informatics-isi-edu/protein-database/files/15275399/pdb_00009a2h_summary_validation.pdf)

Also `--output-prefix` cli key seems to work well. 

The code is in https://github.com/salilab/IHMValidation/tree/dev_2.0_pdbid

There are several moments that we need to clarify:
Related to PDFs:
1. Summary validation has an ID in the header:
```
Summary of integrative structure determination of <...> (ID)
```
Right now, I set it up to select the first existing ID in the list: database2 PDB ID, database2 PDBDEV ID, and entry_id. Is this logic okay? If there are both PDB and PDBDEV IDs, should I print both of them?

Related to HTMLs (in the future):
1. I will need to update links in the HTML templates to be in sync with the IDs/link schemes used on a website. There are several places where links with explicit IDs are used (for instance, on the main.html page). 
![2024-05-10-061753_672x749_scrot](https://github.com/informatics-isi-edu/protein-database/assets/578484/5dc7f8df-a11f-4987-98be-6c1bec194c41)


Also,

**Comment by brindakv** [comment]
@aozalevsky The IHMCIF files corresponding to remediated PDB-Dev entries are available on the RCSB cloud docker instance under `/mnt/vdb1/mmcif/pdb_id_remediation`.

Please use these for generating validation reports version 1.2.

**Comment by brindakv** [comment]
@aozalevsky The title in the summary validation report does not clearly identify PDB ID and PDB-Dev ID. This needs to be addressed.

**Comment by aozalevsky** [comment]
@brindakv can you give me an example? like that?

```
Summary of integrative structure determination of Model of E. coli GlgA by in-cell
photo-crosslinking MS and deep learning (PDB ID: 9A2H; PDB-Dev ID: PDBDEV_00000166)
```

and (if both a missing):
```
Summary of integrative structure determination of Model of E. coli GlgA by in-cell
photo-crosslinking MS and deep learning (Entry ID: TEST-XXX1)
```

**Comment by brindakv** [comment]
The first example looks good. 

In the second one, perhaps use `Entry ID: NONE` or `Entry ID: MODEL`.

**Comment by aozalevsky** [comment]
@brindakv 

test examples. 

![image](https://github.com/informatics-isi-edu/protein-database/assets/578484/994cce33-0e9a-4a15-bb68-66c94555e2e7)
![image](https://github.com/informatics-isi-edu/protein-database/assets/578484/1497d4d1-94fb-49d7-ab19-515346a5852d)

Adjusting linebreaks might be tricky, but I can try.

**Comment by brindakv** [comment]
@aozalevsky I see your point. Please use `_entry.id` from the file.

**Comment by brindakv** [comment]
The examples look good.

**Comment by brindakv** [comment]
@aozalevsky Is the code updated in the backend pipeline on `dev`?

**Comment by aozalevsky** [comment]
@brindakv yes. i've pushed and pulled the update.

**Comment by aozalevsky** [comment]
both `dev` and `production` are running [v1.2](https://github.com/salilab/IHMValidation/releases/tag/v1.2)
