### ISSUE TITLE
Workflow issue on production

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#217]
On production, when curator changes the workflow status to `Submission Complete`, the backend process updates the workflow status first to `mmCIF Created` before changing to `HOLD` on production. 

This should not happen based on this [state diagram](https://docs.google.com/drawings/d/1_g8Mq8cHgA3a1LdIceXkmAkZS9lFgci0paxP_B3URSs/edit?usp=sharing). 

It should go to `HOLD` directly without going to `mmCIF Created.`

**Comment by hongsudt** [comment]
Brinda, can you verify whether this is also happening on dev?

This could be due to the different versions deployed.. It is unlikely since
we just recently deployed to production, but it is good to verify that it
is the latest code.

**Comment by brindakv** [comment]
We also got an automated email from the system that workflow status was changed to `mmCIF Created` for entry `2-TDJC` on production. This happened before it went to `HOLD`. 

I have to test this on `dev`.

**Comment by brindakv** [comment]
@hongsudt This happens on `dev` too. See the history of `entry.Workflow_Status` for RID `2-KXKG` on `dev` and the same for entry `2-TDJC` on production.

**Comment by svoinea** [comment]
Problem should be fixed at this time on `dev` (catalog `99`).

**Comment by svoinea** [comment]
The problem should be fixed at this time on catalog `99`. I have suppressed one of the emails.

**Comment by brindakv** [comment]
Thanks @svoinea. 

@monica81567 Please test with again with another entry.

**Comment by monica81567** [comment]
I tried one of Kolja's entry so it would go faster and got error.  The error doesn't have a detailed error message.

![image](https://github.com/informatics-isi-edu/protein-database/assets/103751282/aa1f445c-f662-43cd-9566-6fab48a95b4d)

**Comment by brindakv** [comment]
@monica81567 Please test this again.
