### ISSUE TITLE
Matrix data are missing in ermrest -- ingest pipeline

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#219]
It seems like there are missing data for columns that contains `[]` e.g `vector[1]`
@brindakv please update the issue with the chaise link to show the table with missing matrix data.  Please also put the RID/link of Arthur's mmCIF file that contains the matrix data.

We will proceed with the following:
- [ ] @svoinea sends @brindakv the json output before the ingest to ermrest step
- [ ] @brindakv checks mmCIF table names and column names against what's in the ermrest- https://data.pdb-dev.org/ermrest/catalog/1/schema/PDB 
  - Use only table/column names that starts with lower case. 
  - This is to ensure that the ingest process of those inconsistent columns are in-tact or should be handled properly. 

Example entry: https://data.pdb-dev.org/chaise/record/#1/PDB:entry/RID=2-RW4P
Input file that contains the matrix: https://data.pdb-dev.org/hatrac/pdb/submitted/uid/442a6439-c239-4ff0-af85-d479bc676497/entry/mmCIF/5d666c6000e0f94bdddbbc970f1c6cac.cif:V652CQEG4XJRMHQDDUSOZDSZGU?uinit=1&cid=record
Table with missing data: https://data.pdb-dev.org/chaise/recordset/#1/PDB:ihm_2dem_class_average_fitting/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JHQBcAjdafEABQBEAhEAGhAEsALAWwH0AmKHblgA2YJEi5gAbjgxgA5ji4AzFkSIsIcrkiIY0WIpkUsoygNY4AniAC6AX2YAlAJI1bzLGxQtcSSjwBaRwB1ABYqWzt7IA@sort(RID)

**Comment by svoinea** [comment]
Tables in `ermrest` but not in `json-full-db-ihm_dev_full-col-ihm_dev_full.json`:
```
[
    "Accession_Code",
    "Conform_Dictionary",
    "Curation_Log",
    "Data_Dictionary",
    "Entry_Error_File",
    "Entry_Generated_File",
    "Entry_Related_File",
    "Entry_Related_File_Templates",
    "Supported_Dictionary",
    "ihm_data_transformation",
    "ihm_entry_collection",
    "ihm_entry_collection_mapping",
    "ihm_hdx_restraint"
]
```
`ihm_entry_collection` and `ihm_entry_collection_mapping` are written in the system generated mmCIF through a special function `addCollectionRecords` that is doing a join `entry JOIN ihm_entry_collection_mapping JOIN ihm_entry_collection`.

`ihm_data_transformation` and `ihm_hdx_restraint` are `NOT` written in the system generated mmCIF.

If those two tables need to be written in the system generated mmCIF, ideally they should be present in the `json-full-db-ihm_dev_full-col-ihm_dev_full.json` file.

**Comment by svoinea** [comment]
None of the `mmCIF` files on catalog `1` contains references to the `ihm_data_transformation` or `ihm_hdx_restraint` tables.

**Comment by brindakv** [comment]
@svoinea This check was supposed to be for entries with data populated for tables `ihm_data_transformation` and `ihm_hdx_restraint` in ermrest and not in mmCIF files.

**Comment by brindakv** [comment]
@svoinea Matrix data are still missing on ingest: https://dev-aws.pdb-dev.org/chaise/record/#99/PDB:entry/RID=3-8TET. 

The user-uploaded mmCIF file contains data for these tables:
```
ihm_data_transformation
ihm_geometric_object_transformation
ihm_hdx_restraint
```

But there is no data in these tables in ermrest for this entry. Other tables loaded fine without any error. 

There seems a problem with `make-mmcif.py` and data is missing in `output.cif` when I run it locally. I have raised an issue [here](https://github.com/ihmwg/python-ihm/issues/143).
