### ISSUE TITLE
Workflow status

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#22]
A column needs to be added to the "Entry" table to handle workflow status. The "Entry" table is the parent table with incoming foreign keys from all other tables. The workflow status needs to be inherited by all the other tables related to the entry.

**Comment by svoinea** [comment]
Suggested name for the column: `workflow_status`.

**Comment by brindakv** [comment]
Agreed.

**Comment by hongsudt** [comment]
Is this the same as curation status?

**Comment by brindakv** [comment]
Yes

**Comment by hongsudt** [comment]
We could have different status associated with the execution mmCIF workflow. So if you don't have issue with the word `Curation_Status`, should we converge on using that term?

**Comment by svoinea** [comment]
The `workflow_status` column was added to the `entry` table as a FK to the vocabulary `workflow_status` table.

**Comment by brindakv** [comment]
`workflow_status` shows `Record Ready` but none of the tables from step 2 are populated.
