### ISSUE TITLE
Missing content in generated mmCIF

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#220]
Because of the out-of sync matrix column names in the tables.json config file and the ermrest model (e.g. the column names were changed from "Matrix_1_1" to "Matrix[1][1]" 2 years ago (#113)), the data were not properly exported into mmCIF file. 

@svoinea please update the issue with the link to the config file (I think it is tables.josn) in the issue. 

- [ ] @svoinea fix the config file to reflect proper column names
- [ ] @svoinea compares the config file with the ermrest model to check what are other missing tables that should have been included in the mmCIF file
- [ ] For short term, update the config file with those missing tables.
- [ ] Longer term plan is to treat this config file for optional column sorting config, not the source of what data to be exported. mmCIF doesn't require the columns to be in any particular order.

**Comment by svoinea** [comment]
[prep-PDBDEV_00000211-ihm_dev-ihm_dev-.json](https://github.com/informatics-isi-edu/protein-database/files/15284305/prep-PDBDEV_00000211-ihm_dev-ihm_dev-.json)

@brindakv  I have attached the `*.json` file that results after executing the `testSchemaDataPrepValidate-ihm.py` command.

The matrix table is `ihm_2dem_class_average_fitting`.
The `deposition.cif` contains the columns names in the matrix format (for example `rot_matrix[1][1]`.
Same with the `output.cif` that results after executing the `make-mmcif.py deposition.cif` command.

The resulted `*.json` file contains the columns names in the format of the original provided schema (for example `rot_matrix_1_1`).

That explains the missing values in the `ermrest` DB.

**Comment by svoinea** [comment]
All the data was taken from catalog `1`.

Records of the `entry` table which `mmCIF` files contain the tables with column names containing square brackets:
```
{
    "ihm_geometric_object_transformation": [
        "PDBDEV_00000213",
        "3-7VYR",
        "PDBDEV_00000012",
        "PDBDEV_00000011",
        "PDBDEV_00000010"
    ],
    "ihm_data_transformation": [],
    "ihm_2dem_class_average_fitting": [
        "PDBDEV_00000016",
        "PDBDEV_00000012",
        "PDBDEV_00000011",
        "PDBDEV_00000010",
        "PDBDEV_00000001",
        "PDBDEV_00000211"
    ]
}
```
The values are the `Accession_Code` with the exception of one entry that has no `Accession_Code` and for which I have provided the `RID` (`3-7VYR`).

The `structure_id` of the `ihm_geometric_object_transformation` table which have at least one column `not null`:
```
_ermrest_catalog_1=> select distinct structure_id from ihm_geometric_object_transformation where
"rot_matrix[1][1]" is not null or
"rot_matrix[1][2]" is not null or
"rot_matrix[1][3]" is not null or
"rot_matrix[2][1]" is not null or
"rot_matrix[2][2]" is not null or
"rot_matrix[2][3]" is not null or
"rot_matrix[3][1]" is not null or
"rot_matrix[3][2]" is not null or
"rot_matrix[3][3]" is not null or
"tr_vector[1]" is not null or
"tr_vector[2]" is not null or
"tr_vector[3]" is not null
order by structure_id
;
  structure_id   
-----------------
 D_2-8SC8
 PDBDEV_00000010
 PDBDEV_00000011
 PDBDEV_00000012
(4 rows)
```
The `structure_id` of the `ihm_geometric_object_transformation` table which have all columns `null`:
```
_ermrest_catalog_1=> select distinct structure_id from ihm_geometric_object_transformation where
"rot_matrix[1][1]" is null and
"rot_matrix[1][2]" is null and
"rot_matrix[1][3]" is null and
"rot_matrix[2][1]" is null and
"rot_matrix[2][2]" is null and
"rot_matrix[2][3]" is null and
"rot_matrix[3][1]" is null and
"rot_matrix[3][2]" is null and
"rot_matrix[3][3]" is null and
"tr_vector[1]" is null and
"tr_vector[2]" is null and
"tr_vector[3]" is null
order by structure_id
;
 structure_id 
--------------
 D_3-7VYR
(1 row)
```
The `structure_id` of the `ihm_2dem_class_average_fitting` table which have at least one column `not null`:
```
_ermrest_catalog_1=> select distinct structure_id from ihm_2dem_class_average_fitting where
"rot_matrix[1][1]" is not null or
"rot_matrix[1][2]" is not null or
"rot_matrix[1][3]" is not null or
"rot_matrix[2][1]" is not null or
"rot_matrix[2][2]" is not null or
"rot_matrix[2][3]" is not null or
"rot_matrix[3][1]" is not null or
"rot_matrix[3][2]" is not null or
"rot_matrix[3][3]" is not null or
"tr_vector[1]" is not null or
"tr_vector[2]" is not null or
"tr_vector[3]" is not null
order by structure_id
;
  structure_id   
-----------------
 PDBDEV_00000001
 PDBDEV_00000010
 PDBDEV_00000011
 PDBDEV_00000012
 PDBDEV_00000016
(5 rows)
```
The `structure_id` of the `ihm_2dem_class_average_fitting` table which have all columns `null`:
```
_ermrest_catalog_1=> select distinct structure_id from ihm_2dem_class_average_fitting where
"rot_matrix[1][1]" is null and
"rot_matrix[1][2]" is null and
"rot_matrix[1][3]" is null and
"rot_matrix[2][1]" is null and
"rot_matrix[2][2]" is null and
"rot_matrix[2][3]" is null and
"rot_matrix[3][1]" is null and
"rot_matrix[3][2]" is null and
"rot_matrix[3][3]" is null and
"tr_vector[1]" is null and
"tr_vector[2]" is null and
"tr_vector[3]" is null
order by structure_id
;

 structure_id 
--------------
 D_2-RW4P
(1 row)
```
There are no rows in the `ihm_data_transformation` table in `ermrest`.

**Comment by aozalevsky** [comment]
@brindakv @svoinea new `py-rcsb_db` version https://salilab.org/~arthur/ihmv/packages/py-rcsb_db_v0.87.tar.gz

**Comment by brindakv** [comment]
Data to be fixed: 
    "ihm_geometric_object_transformation": 
        "PDBDEV_00000213" - fix
        "3-7VYR", - ignore
        "PDBDEV_00000012" - ignore
        "PDBDEV_00000011" - ignore
        "PDBDEV_00000010" - ignore

    "ihm_2dem_class_average_fitting": 
        "PDBDEV_00000016" - ignore
        "PDBDEV_00000012" - ignore 
        "PDBDEV_00000011" - ignore 
        "PDBDEV_00000010" - ignore 
        "PDBDEV_00000001",
        "PDBDEV_00000211" - fix

**Comment by brindakv** [comment]
> @svoinea will do a recursive grep on hatrac user deposited mmCIF files for the table names identified (e.g., ihm_2dem_class_average_fitting)

@svoinea Was this done? What were the results?

**Comment by svoinea** [comment]
Based on the previous comment, the result is to review the entries with the `Accession_Code` equal to `PDBDEV_00000213` for the `ihm_geometric_object_transformation` table and `PDBDEV_00000211` to the `ihm_2dem_class_average_fitting` table.

**Comment by brindakv** [comment]
@svoinea I am trying to make sure that entries with the Accession_Code equal to `PDBDEV_00000213` and `PDBDEV_00000211` are the only problematic cases. 

For this, I don't think the ermrest queries above are sufficient. The user deposited mmCIF files in hatrac is the primary source and a recursive grep will provide the right answer.

**Comment by svoinea** [comment]
@brindakv I am not sure what you mean by `I don't think the ermrest queries above are sufficient`. The `hatrac` might have `multiple` versions of the `same` file. I handled only the `last` one, based on the value from the `ermrest` DB.

**Comment by svoinea** [comment]
@aozalevsky I am getting this error trying to get the file on the Ubuntu `dev` instance:
```
$ wget https://salilab.org/~arthur/ihmv/packages/py-rcsb_db_v0.87.tar.gz
--2024-06-03 09:05:19--  https://salilab.org/~arthur/ihmv/packages/py-rcsb_db_v0.87.tar.gz
Resolving salilab.org (salilab.org)... 169.230.79.19
Connecting to salilab.org (salilab.org)|169.230.79.19|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-06-03 09:05:19 ERROR 403: Forbidden.
```

**Comment by aozalevsky** [comment]
@svoinea fixed

**Comment by svoinea** [comment]
@aozalevsky Thanks.

**Comment by aozalevsky** [comment]
@svoinea @brindakv i've uploaded updated [py-rcsb_db_v0.87.tar.gz](https://salilab.org/~arthur/ihmv/packages/py-rcsb_db_v0.87.tar.gz) (`md5sum a8f40d0464241a460536f97fa93a5e3c`) and verified the permissions.
