### ISSUE TITLE
Add Manual_Processing to Entry table to stop pipeline processing

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#222]
Given that we will have so many entries that are manually curated, it might be safer to add the checking in the processing pipeline not address this (so that the uploaded docs will not be over-written). 

Let's add Manual_Processing : Boolean (default False) to the Entry table. 
Manual_Processing: comment = True indicates that the entry processing including generated files will be handled by curators
Update ACL to only allow curators to view and edit.

We add this to the task selection criteria e.g. only entries with Manual_Processing=False and whatever processing status we are using (New/Renew/Resume?)? 

We should also add this checking at the beginning of the processing pipeline, in case it gets triggered somehow. Set the status to "Error: manual processing is true"? 

Update Process Status trigger to handle manual processing.

**Comment by svoinea** [comment]
Ready for test on catalog `99`.

**Comment by brindakv** [comment]
Works on catalog `99` in `pdb` mode. 

`entry.Process_Status` is a bit misleading when backend processing is stalled: `Resume (trigger backend process)`.

**Comment by brindakv** [comment]
When `manual processing` is set to `true`, the backend workflow stops. 

But setting it to `false` does not re-trigger the workflow on it's own unless `Workflow Status` is updated simultaneously (e.g., from `Submission Complete` to `Submit`).  

This behavior is ok. This is just an fyi for curators. @monica81567 please note that this will effective on production once deployed.
