### ISSUE TITLE
Cannot delete entries on dev server

### ISSUE THREAD

**Issue by monica81567** [informatics-isi-edu/protein-database#226]
Tried to delete this entry using the delete button within the entry:
https://dev-aws.pdb-dev.org/chaise/record/#99/PDB:entry/RID=3-914E
![image](https://github.com/informatics-isi-edu/protein-database/assets/103751282/61b9fb83-ce5f-48d0-8a43-d3b8a04824df)

And also tried to use the trashcan button on the main entry page:
https://dev-aws.pdb-dev.org/chaise/recordset/#99/PDB:entry@sort(RCT::desc::,RID)
![image](https://github.com/informatics-isi-edu/protein-database/assets/103751282/9efdd7d4-bd74-4ee7-9bfb-da7616d00e8a)

It asked me to Confirm delete, but there is no way to confirm it.  See attached screenshot.

![image](https://github.com/informatics-isi-edu/protein-database/assets/103751282/e10905c9-f7f8-44e7-954a-a1088229c17f)

**Comment by svoinea** [comment]
On my Mac Workstation, the buttons are visible:

<img width="1134" alt="Screenshot 2024-06-11 at 10 24 35 AM" src="https://github.com/informatics-isi-edu/protein-database/assets/1609577/3ecf435d-16f3-48ee-acb9-0f768322f781">

**Comment by RFSH** [comment]
Thank you for reporting the issue. 

This happens because the "Confirm Delete" modal content is not scrollable. So, depending on your screen size, the button might not be visible. We pushed a change to make the content scrollable. 

I think we're using automatic daily updates on this server, so you should be able to see the change tomorrow.

**Comment by monica81567** [comment]
Thank you for making it scrollable.  I just re-tested and can confirm that if I use control minus, then the warning will fit in the window and I can see the delete button.
