### ISSUE TITLE
Extend ENTRY table for Assets for mmCIF file, image, etc

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#23]
Assets need to be created in the ENTRY table for mmCIF coordinate file and an image file.

**Comment by svoinea** [comment]
Suggested names for the two columns:
 - `Image_File_Name`
 - `Coordinates_File_Name`

Related to the `asset` property, there will be also columns for the files `size` and `md5`.

Example of asset annotation for the image file:
```
    "tag:isrd.isi.edu,2017:asset": {
      "md5": "Image_File_MD5",
      "url_pattern": "/hatrac/resources/images/{{$moment.year}}/{{{Image_File_MD5}}}",
      "filename_column": "Image_File_Name",
      "byte_count_column": "Image_File_Size"
    }
```
While uploading, the `url_pattern` shows the location where the file will be placed.
Usually it is on `hatrac` using the `md5` as the name.
If you want to group them based on the year when they were uploaded, you are using in the path `{{$moment.year}}`.

**Comment by brindakv** [comment]
`Image_File_URL` is fine. The second one should be `mmCIF_File_URL`.

**Comment by brindakv** [comment]
It is not the ENTITY table, but the ENTRY table.

**Comment by hongsudt** [comment]
@svoinea please add some more information on columns that we might need to do off-line processing of those mmCIF and Image file?

**Comment by svoinea** [comment]
The `entry` table was extended with the above mentioned columns.

**Comment by hongsudt** [comment]
@svoinea raised the issue of how can we identify whether a mmCIF file has been uploaded for re-processing. There are 2 ways to do it. 
- Create a trigger that upon insert, check whether the file content has changed. If so, set the Process_Status to Retry. 
- Create another column i.e. Processed_File_MD5 to maintain the MD5 of the file that it last processed. When the processing is triggered, it will also check for those Error cases that have File_MD5 that is different from Processed_File_MD5. 

I think the first option is cleaner and is easier to maintain. 

There was also a question of how to let users know of what cause the processing failure. This meaningful error message should be set using the Record_Status_Detail. A successful retry should set Record_Status_Detail to NULL.

**Comment by carlkesselman** [comment]
hmmm… as you know, I’m not a big fan of triggers as they break our model. Is this something that could be done with the message bus?

Carl


----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On May 4, 2020, 6:57 PM -0700, Hongsuda <notifications@github.com>, wrote:
@svoinea<https://github.com/svoinea> raised the issue of how can we identify whether a mmCIF file has been uploaded for re-processing. There are 2 ways to do it.
• Create a trigger that upon insert, check whether the file content has changed. If so, set the Process_Status to Retry.
• Create another column i.e. Processed_File_MD5 to maintain the MD5 of the file that it last processed. When the processing is triggered, it will also check for those Error cases that have File_MD5 that is different from Processed_File_MD5.
I think the first option is cleaner and is easier to maintain.
There was also a question of how to let users know of what cause the processing failure. This meaningful error message should be set using the Record_Status_Detail. A successful retry should set Record_Status_Detail to NULL.

**Comment by hongsudt** [comment]
I am aware of your preference.. We could do a non-trigger approach (which is the second option) but it is awkward and could lead to errors as we need to keep track of the value before and after changes.

In this case, a trigger is very simple as it allows you to access the before and after values while doing an update statement.

________________________________

**Comment by svoinea** [comment]
On catalog `99` I have defined triggers for `insert` and `update`.

**Comment by brindakv** [comment]
When a processing error occurs with the uploaded mmCIF file, all records populated using the mmCIF file, should be deleted / rolled back. This can be carried out either when the error occurs or when the user uploads a new file. The error is conveyed to the user through `Process status` and `Record status detail`.

**Comment by hongsudt** [comment]
To prevent having an entry record without the actual mmCIF file, we will make the mmCIF mandatory. @brindakv will back update this field for the existing Entry rows. Then @svoinea will make the mmCIF_File_URL a key column.

**Comment by hongsudt** [comment]
@svoinea have we added the Accession_Code to this table?

**Comment by brindakv** [comment]
The `entry` table needs a column `workflow status detail` or to capture the errors while processing the uploaded `mmCIF` file. It can be set to null when there are no errors.

**Comment by svoinea** [comment]
The `Record_Status_Detail` column was added to capture the error details.
