### ISSUE TITLE
create Vocab:workflow_status_term vocab table

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#24]
Create `Vocab:workflow_status_term` vocab table to track curation states. Please set all the comments associated with each column to NULL; as the default comments are not useful. 

These are the Name and Description of entries to be added to the table. 

- DRAFT: User is adding/updating/removing data
- DEPO: Deposit data for automated backend process
- RECORD READY: Automated backend process complete and ready for review
- ERROR: Error processing uploaded file
- SUBMIT: User has completed deposition and submitted the entry for processing
- mmCIF CREATED: Export to mmCIF complete
- PROC: Entry is being processed by curator
- HOLD: Entry is on hold for publication
- REL: Entry is released after publication

Note: See the detail in the google slide: 
https://docs.google.com/presentation/d/13x0-6285zmdRYer0Sc2R223kfntFOvh0/edit#slide=id.p1

**Comment by svoinea** [comment]
To be consistent with the current naming convention of the vocabulary tables, should this table not be finally named `entry_workflow_status`? So far, we named the vocabulary tables as `<parent_table_name>_<term_table_name>` truncating the beginning of the `<parent_table_name>` if necessary.

**Comment by brindakv** [comment]
Yes, it should be `entry_workflow_status`.

**Comment by svoinea** [comment]
Is it `EXPORTED` also a status in the table? I saw it present in the slide `3`. If YES, please provide a description for it.

**Comment by brindakv** [comment]
@svoinea we are still working out the terms.

**Comment by hongsudt** [comment]
Sorry.. I didn't see your question about the table name. No, we shouldn't name the workflow_status entry_workflow_status, as the terms are not necessary specific to entry only.

Generally, the terms can be used as fk for many tables.

@Brinda Vallat<mailto:brinda.vallat@rcsb.org> Are those nomenclature so unique to different tables and columns so that they never share?


________________________________

**Comment by brindakv** [comment]
@hongsudt I see your point. You are suggesting that workflow_status should be an independent vocab table and can have fkeys from any other table, entry being one such table. My previous answer to @svoinea was before our discussion today.  

Regarding the nomenclature, at present I don't see any requirement for workflow_status terms to be unique to a given table. However, I am not sure what step 4 (csv/tsv file upload) will entail and if any special terms are required to handle that process. Even then, I think the terms can be generic and not specific to any particular table.

**Comment by svoinea** [comment]
The vocabulary `workflow_status` was created and all the vocabulary tables were renamed (removed the `_term` suffix as well as the comments of the `Name` and `Description` columns were set to `null`.

**Comment by hongsudt** [comment]
@brindakv please review.

**Comment by brindakv** [comment]
@svoinea could you please point me to the URL for the `workflow_status` vocab table?

**Comment by brindakv** [comment]
Looks good to me.

**Comment by brindakv** [comment]
Add `Error` to the `workflow_status` vocab table (see description above).
