### ISSUE TITLE
Rename Vocab tables and constraint names

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#25]
- identify the vocab tables to be renamed
- come up with naming strategy (@brinda helps with this)

**Comment by svoinea** [comment]
[vocabulary_tables.txt](https://github.com/informatics-isi-edu/protein-database/files/4372648/vocabulary_tables.txt)

The attached file (a `json` file but I need to change its extension to `txt` as github  does not accept the `json` extension) contains the vocabulary tables as extracted from the `json-full-db-ihm_dev_full-col-ihm_dev_full.json` file.

The key of each entry is the table name formed by joining the `parent` with the `term` by `_`. 

For each entry you will find its key length, the table name in the database having the suffix `term` and being truncated, its parent and its term.

Total number of files: `79`.

There are only `4` tables with names `>=55`:
```
Table ihm_geometric_object_distance_restraint_group_conditionality, Name length: 60
Table ihm_geometric_object_distance_restraint_object_characteristic, Name length: 61
Table ihm_model_representation_details_model_object_primitive, Name length: 55
Table ihm_starting_comparative_models_template_sequence_identity_denominator, Name length: 70
```

**Comment by brindakv** [comment]
For the remaining 4 table names, we could use the following: 
`geometric_object_distance_restraint_group_condition`
`geometric_object_distance_restraint_object_character`
`model_representation_details_model_object_primitive`
`starting_comparative_models_template_sequence_id_denom`

**Comment by svoinea** [comment]
The vocabulary tables were renamed accordingly as well as the constraints referring to them.

**Comment by brindakv** [comment]
Looks good to me.
