### ISSUE TITLE
File submission table (Entry_Related_File)

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#26]
Entry_Related_File:

- File_Type : e.g. ihm_entity_poly_segment, ihm_cross_link_list, ihm_cross_link_restraint, ihm_cross_link_result, etc --> Use the list the tables in Step 4 for File_Type content
- File_Format: e.g. tsv/csv
- File_URL
- File_Name
- File_MD5
- File_Bytes
- Workflow_Status --> fk to 'Vocab:entry_workflow_status_term`
- Process_status --> (i.e. New, Processing, Success, Failure)
- Record Status Detail (markdown---null means no problem)
- Description (text field for user to provide a description about the file)

Name spaces 
  - Entry_Related_Files: `/hatrac/pdb/entry_files/<submission_year>/<File_MD5>`
  - For reference: 
    - mmCIF files: `/hatrac/pdb/mmCIF/<submission_year>/<File MD5>`
    - Image files: `/hatrac/pdb/image/<submission_year>/<File_MD5>`

Vocab:File_Type (will be used to capture File_Type)
- Name
- Description

Vocab:File_Format (for csv/tsv)
- Name
- Description

Create "Entry_Related_File" column for all tables populated in step 4. 
This "Entry_Related_File" column should be a FK pointing to the RID of the Entry_Related_File table. Make the fk cascade on delete.

**Comment by svoinea** [comment]
The `PDB.Entry_Related_File` table was created as well as the `Vocab.File_Type` and `Vocab.File_Format` ones.

The tables from step 4 were extended with the column `Entry_Related_File` as a FK pointing to the `RID` of the `Entry_Related_File` table.

**Comment by brindakv** [comment]
`PDB.Entry_Related_file` should have another column `structure_id` with outgoing fkey to `entry.id`.

**Comment by svoinea** [comment]
For the catalog `99`:
 - the column `structure_id` was added
 - the Foreign Key `PDB.Entry_Related_File.structure_id --> entry.id` was added
 - the `structure_id` column was added in the list of the visible columns annotation

**Comment by brindakv** [comment]
The `structure_id` column is not found in the `Entry_Related_File` table in catalog 99.

**Comment by brindakv** [comment]
`pdb-submitter` does not have access to the `Entry Related File` table in catalog 99.

**Comment by svoinea** [comment]
The `Forbidden` bug was corrected.

**Comment by brindakv** [comment]
@svoinea, as discussed today, please add a field with name "Description" to this table.

**Comment by svoinea** [comment]
I have added the `Description` column and made it visible in the compact, filter, entry and detailed contexts.
