### ISSUE TITLE
Extend IHM_STARTING_MODEL_DETAILS to take mmCIF file

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#27]
Need extra columns to describe the file.. 

- mmCIF_File_URL
- mmCIF_File_Name
- mmCIF_File_Bytes
- mmCIF_File_MD5

**Comment by svoinea** [comment]
The `PDB.ihm_starting_model_details` table was extended with the above mentioned columns.

**Comment by hongsudt** [comment]
@brindakv can you remind me whether this is the place where the export mmCIF will be stored after all the data are submitted?

**Comment by brindakv** [comment]
Issue #21 needs to be fixed before this can be tested. 

@hongsudt no, this not related to storing the exported mmCIF.

**Comment by brindakv** [comment]
Tested and resolved.
