### ISSUE TITLE
Entry table model update

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#28]
`structure_id` is redundant and needs to be removed. 

Every time a new `entry` row is created, it has to trigger a process to auto populate the `id` column. `id` has to follow the format `D_integer`, where the integer is a counter that is incrementally increased with each addition and is 8 digits long.

**Comment by carlkesselman** [comment]
Good.  We really should not be using triggers.

Carl


----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On Apr 20, 2020, 2:20 PM -0700, Brinda Vallat <notifications@github.com>, wrote:

structure_id is redundant and needs to be removed.

Every time a new entry row is created, it has to trigger a process to auto populate the id column. id has to follow the format D_integer, where the integer is a counter that is incrementally increased with each addition and is 8 digits long.

**Comment by brindakv** [comment]
@carlkesselman Is there an alternative to triggers?

**Comment by svoinea** [comment]
An alternative might be to define the `DEFAULT` for the `id` column as a function and hide the `id` column while inserting or updating a row in the `entry` table. It is similar with the way the `RID` values are generated.

**Comment by brindakv** [comment]
@svoinea let's do the same method as the `RID` values.

**Comment by brindakv** [comment]
A new column, called `accession_code` needs to be added to the `entry` table.

**Comment by brindakv** [comment]
The `id` column should follow the format `D_RID` rather than `D_integer`.

**Comment by svoinea** [comment]
An `insert` trigger for generating the `id` in the format `D_<RID>` was defined for catalog `99`.
