### ISSUE TITLE
Mandatory mmCIF files in Entry table

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#29]
`mmCIF file` should be mandatory in the `entry` table. 

Before updating the mandatory condition, mmCIF files need to be uploaded for existing entries in catalog 99. `Workflow status` needs to be set to `HOLD` before uploading the files in order to avoid auto-updating other tables related to the entry.

**Comment by brindakv** [comment]
`mmCIF` files have been added to all rows in the `entry` table in catalog 99. `Workflow status` has been set to `HOLD` for the same. 

@svoinea It should now be possible to make `mmCIF File URL` mandatory.

**Comment by svoinea** [comment]
The `mmCIF File URL` column was annotated as required.
