### ISSUE TITLE
Optimize access control for auto-populated tables

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#30]
Auto-populated tables currently allow for manual addition / deletion of rows by users, which can lead to accidental changes. It may be possible to reduce errors by controlling write access to specific tables. Need to review access control for auto-populated tables.

**Comment by svoinea** [comment]
The following tables were annotated as `generated`:
 - entity_poly
 - entity_poly_seq
 - pdbx_poly_seq_scheme
 - chem_comp
 - atom_type
 - struct_asym
 - ihm_model_list
