### ISSUE TITLE
mmCIF generation: use Accession_Code for Entry reference

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#31]
Depending on what we can do during export, another solution is to create a composite foreign key of (ID, Access_Code) to all Entry related tables, which will then be available for writing in the mmCIF file.

**Comment by brindakv** [comment]
`mmCIF` file generation gives an error in catalog `50`: `Update error in exportData(): None`
<img width="541" alt="Screen Shot 2020-08-20 at 11 16 46 AM" src="https://user-images.githubusercontent.com/15000874/90790964-abb70b00-e2d6-11ea-9099-2a02ce53dd35.png">

**Comment by svoinea** [comment]
The above error should be fixed at this time.

**Comment by brindakv** [comment]
Reviewed and the error is fixed.
