### ISSUE TITLE
step 2 processing script

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#35]
If the processing script fails, it should delete all the newly created rows in different tables to make sure that the generated data are consistent with the proper mmCIF file uploaded as part of the Entry. 

The script does the following: 
- Sort the related tables to make sure that the leave tables (those that will have fks referenced to) will be created first. 
- For each table generated by the mmCIF to Json, add entries to the db. 
- Keep track of a list of tables created, so that if an error is thrown, it can be rolled back. 

@svoinea Do I cover the key processing steps? 

Improvement in the future:
- Validate the vocabs to ensure that they are consistent with what's in the DB. This step is quite involved. In the meantime, @brindakv will mitigate this risk by making sure that the vocabs are updated in the mmCIF package and our database.

**Comment by svoinea** [comment]
The script is:
 - sorting the tables based on the FK dependencies
 - add the entries from the JSON file into the DB
 - rollback the inserted rows if a failure occurs

**Comment by brindakv** [comment]
The script is not loading all tables in the JSON file into the DB. 

For instance, in entry `D_1-PBTC`, the JSON file contains `citation` table, which is not present in the DB.

**Comment by hongsudt** [comment]
Did you figure out why the Citation table is not updated in the example that Brinda mentioned?
________________________________

**Comment by svoinea** [comment]
Initially, there was a list of tables that were loaded only.

The script was updated to load all the tables from the JSON files, except the `entry` one.
