### ISSUE TITLE
ACL: pdb-submitter should not be allowed to delete files on HATRAC

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#38]
Related to #21 

`pdb-submitter` should only be allowed to create files on `HATRAC`, but not update or delete files. 

At present, the owner of the file can delete but not update files. To enforce no deletion, ownership has to be changed at some point during the workflow.

**Comment by brindakv** [comment]
@svoinea please confirm if this has been implemented.

**Comment by svoinea** [comment]
I confirm that it has been implemented.
