### ISSUE TITLE
ACL: changing workflow status

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#39]
Related to #21 

At present, `pdb-submitter` can change the `workflow status` to any status before `SUBMIT` (for example `DRAFT`, `DEPO`, `RECORD READY`) or after `SUBMIT` (for example `PROC`, `HOLD`, `REL`). 

Although `pdb-submitter` should be able to see own entries in any status, changing `workflow status` should be restricted to `DRAFT`, `DEPO`, `RECORD READY`, and `SUBMIT`.

The problem can be resolved using triggers.

**Comment by svoinea** [comment]
Problem was fixed through `acls`.
@brindakv Please test and let us know if there are still problems.

**Comment by brindakv** [comment]
@svoinea `pdb-submitter` is not able to change `workflow status` to `mmCIF CREATED`, `PROC`, `HOLD` or `REL`. But the user can change status to `ERROR` and `RECORD READY`. Since these are auto generated after backend processing, perhaps these two states should also not be allowed. @hongsudt please suggest.

**Comment by svoinea** [comment]
Fixed the problem such that the `pdb-submitter` can not update the `workflow_status` to `ERROR` or `RECORD READY`.

**Comment by brindakv** [comment]
I reviewed. Looks good.
