### ISSUE TITLE
Ordering of tables and columns within a table

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#4]
Some tables are more important than others and need to be filled first. Similarly, ordering of columns within a table is also important. Furthermore, some columns / tables that are rarely used can be hidden by default.

**Comment by svoinea** [comment]
Can you please provide a list with the tables ordered by their importance as well as a list with the tables that can be hidden?

**Comment by hongsudt** [comment]
- Columns with the same "Attribute Group ID" should be grouped together. 
- The order of the group members should follow their appearance in json schema.

**Comment by svoinea** [comment]
The `JSON` file represents a Python dictionary, and iteration through a dictionary does not preserve the order in which the columns appear in the file.

The solution should be the column definition in the `JSON` file to have an extra key to specify the order in the `visible-columns`.

**Comment by carlkesselman** [comment]
Or use a list?

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jun 12, 2019, at 2:04 PM, svoinea <notifications@github.com<mailto:notifications@github.com>> wrote:


The JSON file represents a Python dictionary, and iteration through a dictionary does not preserve the order in which the columns appear in the file.

The solution should be the column definition in the JSON file to have an extra key to specify the order in the visible-columns.

**Comment by hongsudt** [comment]
@brindakv is going to discuss with John on how to provide the ordering information within the same group; use array instead of dictionary for columns, or providing ordering metadata in the attribute group object.

**Comment by brindakv** [comment]
This has been done using Deriva annotations.
