### ISSUE TITLE
ACL: Modify ACL for tables / columns

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#40]
Only `pdb-admin` and `pdb-curator` should have write access to the following tables / columns. `pdb-submitter` can be allowed to read these tables / columns for entries they submitted. 

```
chem_comp_atom
pdbx_inhibitor_info
pdbx_ion_info
pdbx_protein_info
pdbx_entity_poly_na_type
pdbx_entry_details
audit_conform
entry.accession_code
```

**Comment by svoinea** [comment]
The issue should be fixed now.
