### ISSUE TITLE
Entry_mmCIF_File

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#43]
To store the generated mmCIF_File after all the submission-relevant entries are marked "Submitted".
- Trigger: When Entry.Workflow_Status = Submitted
- After mmCIF is created, change Entry.Workflow_Status = mmCIF_Created 

Table definition
- File_Name
- File_URL
  - namespace: `/pdb/entry_mmCIF/$moment.year` --> contains generated mmCIF related to Entry
- File_MD5
- File_Bytes
- Structure_Id
- mmCIF_Schema_Version (text) --> (e.g. 1.12) 
- Key: (Structure_ID, Version)
- FK: (Structure_ID) -> Entry(Id)

Entry
- Workflow_Status  
- Processing_Status --> User_mmCIF_Processing_Status (Upload_mmCIF_Processing_Status) 
- Record_Status_Detail 
- Generated_mmCIF_Processing_Status
- ~Generated_mmCIF_Processing_Detail~

Vocab.Processing_Status  --> storing processing status code (NEW, ERROR, SUCCESS)

**Comment by svoinea** [comment]
Created  the `Entry_mmCIF_File` table.
Added the `Generated_mmCIF_Processing_Status` column to the `entry` table.
Added the `Generated_mmCIF_Processing_Status` column to the list of visible columns of the `entry` table in the `compact` and `detailed` contexts.
Added the `Entry_mmCIF_File` table in the first position of the visible foreign keys of the `entry` table. 
Created the `process_status` vocabulary table.
Added in the `PDB` menu list the `Entry_mmCIF_File` table.
Added in the `Vocab` menu list the `process_status` table.
