### ISSUE TITLE
ACL issues

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#45]
Errors related to ACL issues: 
 - `User` is unable to `edit` data in tables populated by the backed process in `step 1` because these are owned by `pdb-ihm` user. Eg: Editing rows in the `entity` table. 
<img width="1362" alt="Screen Shot 2020-08-20 at 9 58 40 AM" src="https://user-images.githubusercontent.com/15000874/90787955-46ade600-e2d3-11ea-8eb6-5ffd8493f9d3.png">

 - The `struct` table view is different for `admin` and `user`. `Admin` is able to see the rows created by `pdb-ihm` during the backend process in step 1, whereas the `user` is not. 
  
<img width="1082" alt="Screen Shot 2020-08-20 at 9 36 57 AM" src="https://user-images.githubusercontent.com/15000874/90789229-ab1d7500-e2d4-11ea-92ea-f4e083e7a199.png">

<img width="1127" alt="Screen Shot 2020-08-20 at 9 38 09 AM" src="https://user-images.githubusercontent.com/15000874/90789261-b4a6dd00-e2d4-11ea-8c2e-0422e7e8bcc7.png">

 - In the `struct` table, the `user` is able to add a row (status shows success) but the `user` is not able to see the row he/she added. The `user` gets a `Record Not Found` error. No such issues for `admin`. 

<img width="698" alt="Screen Shot 2020-08-20 at 10 01 44 AM" src="https://user-images.githubusercontent.com/15000874/90790510-22073d80-e2d6-11ea-8089-5c7a397c15c2.png">

**Comment by svoinea** [comment]
ACLs are currently not defined for updating records that were generated by the `pdb_ihm` user in the background processes.

The `struct` table had removed the `structure_id` column and ACL needs to be updated accordingly.

**Comment by svoinea** [comment]
Identified the following tables that were missing the `ACL`:
```
pdbx_inhibitor_info
pdbx_entity_poly_na_type
pdbx_ion_info
audit_conform
pdbx_entry_details
pdbx_protein_info
chem_comp_atom
ihm_struct_assembly_details
ihm_model_representation
entity
ihm_model_representation_details
ihm_entity_poly_segment
ihm_model_group
ihm_model_group_link
ihm_modeling_protocol
ihm_struct_assembly
```
Defined the `ACL` for them.

Defined the `ACL` for the `struct` table which has no more the `structure_id` column.
