### ISSUE TITLE
Automated processing of mmCIF file

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#46]
Some of the columns generated by the backend process in step 1 are not populated in the catalog. Eg: `ihm_model_representation_details.entity_poly_segment_id`. It is not clear if the error is in the script provided to process the mmCIF file and create the JSON file or in loading the data to the catalog.

**Comment by svoinea** [comment]
This is due to the fact that those columns are OPTIONAL COMPOSITE FK, and the column referring the `RID` of the leaf table is NULL.

**Comment by brindakv** [comment]
@svoinea can you please clarify if the `ihm_model_representation_details.entity_poly_segment_id` values are present in the mmCIF and JSON files.

**Comment by svoinea** [comment]
Yes. The values are in the JSON file as well as in the database. Just `chaise` does not display them due to reason I mentioned above.

**Comment by svoinea** [comment]
Loaded values for the columns referring the `RID` column of the leaf tables.

Updated the backend script to load values for the columns referring the `RID` column of the leaf tables in `step 2` and `step 4`.

**Comment by brindakv** [comment]
In the existing entries, this issue seems to be fixed. I can see the values in the optional composite fkey column. 

However, when I create a new entry, the issue persists in the columns populated by the backend process in step 1. The optional composite fkey column is still empty.

**Comment by hongsudt** [comment]
@brindakv is this still an issue?

**Comment by brindakv** [comment]
Looks good on Dev.
