### ISSUE TITLE
Update table and column names

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#50]
Make table and column names more descriptive with less mmCIF jargon. Not sure if this can be done using chaise annotations while retaining the current table names in ermrest. 

Make the table comments displayed in line rather than as tool tip. 

Retain CIF names in table comments and provide links to the corresponding table on the [mmCIF resource page](http://mmcif.wwpdb.org).

**Comment by svoinea** [comment]
The annotation for displaying a table or column name is `tag:misd.isi.edu,2015:display`.

Example to display the `Entry_mmCIF_File` table as `Entry mmCIF File`:
```
{
  "tag:misd.isi.edu,2015:display": {
    "name": "Entry mmCIF File"
  }
}
```
In the `Entry_mmCIF_File.py` file, you have to set the line:
```
display = {'name': 'Entry mmCIF File'}
```
By default, it should have been displayed as `Entry Mmcif File`.

Example to display the `Entry_mmCIF_File.mmCIF_Schema_Version` column as `mmCIF Schema Version`:
```
{
  "tag:misd.isi.edu,2015:display": {
    "name": "mmCIF Schema Version"
  }
}
```
In the `Entry_mmCIF_File.py` file, under the `column_annotations`, you have to set for the column `mmCIF_Schema_Version`:
```
     'mmCIF_Schema_Version': {
        chaise_tags.display: {
            'name': 'mmCIF Schema Version'
        }
    }
```
By default, it should have been displayed as `Mmcif Schema Version`.
