### ISSUE TITLE
Identity mandatory tables

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#52]
At present, mandatory columns are clearly identified but mandatory tables are not identified. 

We need to identify the mandatory tables on the UI. 

This also relates to issue #5 to make tables required if a particular criterion is satisfied. For example, if `_ihm_dataset_list.data_type` = "3DEM volume", then `ihm_3dem_restraint` table is required.

**Comment by hongsudt** [comment]
@brindakv this is now addressed, right? Can we close?

**Comment by brindakv** [comment]
@hongsudt yes, this has been addressed.
