### ISSUE TITLE
Update data model

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#54]
The data model needs to be updated to comply with the current [IHM-dictionary](https://github.com/ihmwg/IHM-dictionary). 

Examples of the different kinds of updates involved: 

- Add a row to existing Vocab table: Add values `CYS`, `BMSO` and `DHSO` to `_ihm_cross_link_list.linker_type`
- Add a new table: `ihm_pseudo_site` with columns `_ihm_pseudo_site.id` (key, int), `_ihm_pseudo_site.Cartn_x` (float), `_ihm_pseudo_site.Cartn_y` (float), `_ihm_pseudo_site.Cartn_z` (float), `_ihm_pseudo_site.radius` (float), `_ihm_pseudo_site.description` (text)
- Add a new column to an existing table with fkey: Add `_ihm_pseudo_site_feature.pseudo_site_id` with fkey pointing to `_ihm_pseudo_site.id`
- Remove columns from an existing table: Remove `_ihm_pseudo_site_feature.Cartn_x`, `_ihm_pseudo_site_feature.Cartn_y`, `_ihm_pseudo_site_feature.Cartn_z`, `_ihm_pseudo_site_feature.radius` and `_ihm_pseudo_site_feature.description`
- Add a new column and a related new Vocab table: `_ihm_cross_link_restraint.pseudo_site_flag` with values `Yes` and `No`

**Comment by svoinea** [comment]
Committed a script at https://github.com/informatics-isi-edu/protein-database/blob/master/config-scripts/schema-updates/model_updates.py to update the model for the above examples.
