### ISSUE TITLE
Create a new table that allows for data to be uploaded as CSV/TSV file

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#55]
When the data model is updated to add a new table, sometimes the new table needs to allow for data to be uploaded as CSV/TSV file through the `Entry_Related_File` table. Apart from creating the right columns and appropriate foreign keys, the backend process that takes the uploaded file and processes it needs to be updated.

**Comment by svoinea** [comment]
In the `Vocab:File_Type` table you need to add a row with the values for the `Table Name"`, `Name` and "Description"

**Comment by brindakv** [comment]
@svoinea is that sufficient for the backend to process these files?

**Comment by svoinea** [comment]
Yes. The backend process is working with the `Entry_Related_File`.
When you create a new record for it, it will have a drop down list for the `File Type` which selects the table name from the `Vocab.File_Type` table.
That is why it is necessary to add in the `Vocab.File_Type` table a record for the new table.

In the `ihm_cross_link_pseudo_site` table you need to add the following column and FK:
```
            Column.define(
            "Entry_Related_File",
            builtin_types.text,
            comment='...',
            nullok=True
        )
 
        ForeignKey.define(["Entry_Related_File"], "PDB", "Entry_Related_File", ["RID"],
                          constraint_names=[["PDB", "ihm_cross_link_pseudo_site_Entry_Related_File_fkey"]],
                          on_update="CASCADE",
                          on_delete="NO ACTION"
        )

```
Suggested links to look for similar definitions (table `ihm_geometric_object_distance_restraint`):
https://pdb.isrd.isi.edu/ermrest/catalog/99/schema/PDB/table/ihm_geometric_object_distance_restraint/column/Entry_Related_File
https://pdb.isrd.isi.edu/ermrest/catalog/99/schema/PDB/table/ihm_geometric_object_distance_restraint/foreignkey

**Comment by brindakv** [comment]
@svoinea, Does the foreign key to `Entry_Related_File` need to be a composite fkey with `structure_id`?

**Comment by brindakv** [comment]
Apart from updating `Vocab:File_Type`, templates need to be added to [here](https://pdb.isrd.isi.edu/chaise/recordset/#99/PDB:Entry_Related_File_Templates@sort(RID)).

**Comment by brindakv** [comment]
Fixed on catalog `99` and the developer documentation has been updated. May need to be manually fixed during staging and production.
