### ISSUE TITLE
Adding records to new tables

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#56]
When trying to add record to newly created table `ihm_cross_link_pseudo_site`, the columns with foreign keys (`restraint_id`, `model_id` etc.) allow for values from other `structure_id` (not belonging to the current structure) to be chosen. It looks like the composite foreign key is not working. Or we are missing some steps when creating new tables.

**Comment by svoinea** [comment]
In the `foreign_key_annotations` section of the `annotation_config.cpp` file, for each composite FK having `structure_id` in it, add an entry like:
```
        {
            "foreign_key": "ihm_cross_link_pseudo_site_model_id_fkey",
            "foreign_key_schema": "PDB",
            "schema": "PDB",
            "table": "ihm_cross_link_pseudo_site",
            "uri": "tag:isrd.isi.edu,2016:foreign-key",
            "value": {
                "domain_filter_pattern": "{{#if _structure_id}}structure_id={{{_structure_id}}}{{/if}}",
                "template_engine": "handlebars"
            }
        },
```
So repeat it for the `ihm_cross_link_pseudo_site_pseudo_site_id_fkey` and `ihm_cross_link_pseudo_site_restraint_id_fkey` constraints.
