### ISSUE TITLE
Drop legacy key in the entity_poly_seq table

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#59]
From #42, to address a key collision: 
```
PRIMARY KEY COLLISIONS TO BE FIXED (TOTAL: 1)

Duplicate combo1 pk: entity_poly_seq_combo1_key

entity_poly_seq_combo1_key: entity_poly_seq(mon_id,num,structure_id,entity_id,RID)
entity_poly_seq_RID_structure_id_key: entity_poly_seq(RID,structure_id)
```

`entity_poly_seq_RID_structure_id_key: entity_poly_seq(RID,structure_id)` seems like a legacy key that is not used / referenced anywhere. Verify and drop.

**Comment by hongsudt** [comment]
@svoinea have we done this? Can this be closed?

**Comment by svoinea** [comment]
The `entity_poly_seq_RID_structure_id_key` primary key was already dropped.
