### ISSUE TITLE
Allow users to upload data in csv, tsv or excel format

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#6]
There are several tables that cannot be manually filled and users may not necessarily have these in JSON or mmCIF format. In such cases, we should allow users to upload the tables in csv, tsv, or excel format.

**Comment by hongsudt** [comment]
start with csv and tsv. mmCIF will be supported later. 
Recommend not to take excel. We can have an instruction page on how they can convert it..

**Comment by hongsudt** [comment]
lower priority than user access issue #8

**Comment by brindakv** [comment]
Duplicate of issue #26
