### ISSUE TITLE
ACL issues with new tables

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#60]
When the data model is updated and new tables are added, `pdb-admin` is able to view/add/edit information in the table. However, `pdb-submitter` is not able to view or add information to these new tables.

**Comment by brindakv** [comment]
ACL needs to be added for new tables as follows: 

1. `ihm_pseudo_site`: ACL should mimic `ihm_cross_link_restraint`
2. `ihm_cross_link_pseudo_site`: ACL should mimic `ihm_cross_link_restraint`
3. `ihm_ensemble_sub_sample`: ACL should mimic `ihm_ensemble_info`
4. `ihm_data_transformation`: ACL should mimic `ihm_related_datasets`
5. `ihm_hdx_restraint`: ACL should mimic `ihm_hydroxyl_radical_fp_restraint`
6. `ihm_derived_angle_restraint`: ACL should mimic `ihm_derived_distance_restraint`
7. `ihm_derived_dihedral_restraint`: ACL should mimic `ihm_derived_distance_restraint`

**Comment by svoinea** [comment]
The script [2021_12_update_acls.py](https://github.com/informatics-isi-edu/protein-database/blob/master/config-scripts/schema-updates/ciff_extension/2021_12_update_acls.py) was created and ran.

**Comment by brindakv** [comment]
There are a few more tables where ACL needs to be added: 
8. `struct_ref`: ACL should mimic `entity_poly`
9. `struct_ref_seq`: ACL should mimic `entity_poly`
10. `struct_ref_seq_dif`: ACL should mimic `entity_poly`

**Comment by brindakv** [comment]
Model updates include adding new columns to existing tables. Such columns are visible to `pdb-admin` but are not visible to `pdb-submitter`. For example, `pseudo_site_flag` column in `ihm_cross_link_restraint` table and `sub_sample_flag` and `sub_sampling_type` columns in the `ihm_ensemble_info` table.

**Comment by svoinea** [comment]
Defined ACLs for the `struct_ref`, `struct_ref_seq`, `struct_ref_seq_dif` as well as for the new vocabulary tables.

**Comment by brindakv** [comment]
Columns still not visible to `pdb-submitter`: 
 - _struct_ref.db_name
 - _struct_ref_seq_dif.details
