### ISSUE TITLE
Need different Hatrac instances or namespaces for dev, staging and production

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#63]
Need different Hatrac instances or namespaces for dev, staging and production.

**Comment by brindakv** [comment]
@svoinea check hatrac namespace for all environments.

**Comment by svoinea** [comment]
I have checked and only `catalog 99 (dev)` has `"hatrac_namespace": "dev"`.
Therefore, production and staging are synchronized from the `hatrac` point of view.

**Comment by hongsudt** [comment]
To summarize the namespaces:
- dev: /hatrac/dev/pdb
- staging and production: /hatrac/pdb

@svoinea please verify. If this is correct, we can close the issue after updating the summary.
