### ISSUE TITLE
Change name from PDB to PDB-Dev

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#64]
The URL needs to be changed from `pdb.isrd.isi.edu` to `pdb-dev.isrd.isi.edu`

Changes needed in top navbar: 

 - Hope page name to be changed from PDB to PDB-Dev
 - Change `PDB` drop down name to `Data Categories`
 - Add `Documentation` drop down 
     - Add link to [`User Guide`](https://docs.google.com/document/d/1577tJoeXxY5MtolMHzJ5000b-dz2M8JrONAyhZRvXVc/)

**Comment by hongsudt** [comment]
@brindakv @svoinea can we close this issue now? I think this is all done, right?
