### ISSUE TITLE
model extension for Dictionary versions

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#68]
Refer to the [google doc high-level discussion](https://docs.google.com/document/d/1VwAMk_rTJ9eXe7tvOPSrSvnKYPxkHxdphYLlY5aGtBA).

Create the following tables: 
- Vocab.Data_Dictionary_Name(Name, Description)
  - names: mmcif_pdbx.dic, ihm-extension.dic, flr-extension.dic
- Vocab.Data_Dictionary_Category(Name, Description)
  - potential names: mmcif, ihm-extension, flr-extension
- PDB.Data_Dictionary (name, version, location, Category)  --> @brindakv should this be in PDB or Vocab schema? 
  - fk from (name) to (Data_Dictionary_Name.Name)
  - fk from (Category) to (Data_Dictionary_Name.Category)
  - key: (name, version), (RID, Category)
  - potential rows: 
```
mmcif_pdbx.dic 5.311  http://mmcif.wwpdb.org/dictionaries/ascii/mmcif_pdbx_v50.dic
ihm-extension.dic 1.0    https://github.com/ihmwg/IHM-dictionary/blob/master/ihm-extension.dic
```
- PDB.Supported_Dictionary (Data_Dictionary_RID, Data_Dictionary_Category)
  - key: (Data_Dictionary_Category) --> there can only one row for each category
  - fk: (Data_Dictionary_RID, Data_Dictionary_Category) to (Data_Dictionary.RID, Data_Dictionary.Category)
- PDB.Conform_Dictionary (Exported_mmCIF_RID, Data_Dictionary_RID)
  - fk: (Exported_mmCIF_RID) to (Exported_mmCIF.RID)
  - fk: (Data_Dictionary_RID) to (Data_Dictionary.RID)
  - key: (Exported_mmCIF_RID, Data_Dictionary_RID)

Note: PDB.Exported_mmCIF (not sure it is the right table name) ==> eventually, we might want to drop the existing text field for capturing the IHM-Dict version. 

@svoinea please review

**Comment by brindakv** [comment]
> Values for `Vocab.Data_Dictionary_Name`:
> 
> ```
>      Name     
> -------------------
>  ihm-extension.dic
>  mmcif_pdbx.dic
> ```
> 
> Values for `Vocab.Data_Dictionary_Category`:
> 
> ```
>      Name     
> -------------------
>  ihm-extension
>  mmcif_pdbx
> ```
> 
> Values for `PDB.Data_Dictionary`:
> 
> ```
>      Name          |   Category    | Version      |                             Location                             
> -------------------+---------------+--------------+-----------------------------------------------------------------------
>  ihm-extension.dic | ihm-extension | 1.0          | https://github.com/ihmwg/IHM-dictionary/blob/master/ihm-extension.dic
>  ihm-extension.dic | ihm-extension | 1.01         | https://github.com/ihmwg/IHM-dictionary/blob/master/ihm-extension.dic
>  mmcif_pdbx.dic    | mmcif_pdbx    | 5.311        | http://mmcif.wwpdb.org/dictionaries/ascii/mmcif_pdbx_v50.dic
>  mmcif_pdbx.dic    | mmcif_pdbx    | 5.313        | http://mmcif.wwpdb.org/dictionaries/ascii/mmcif_pdbx_v50.dic
> ```
> 
> Values for `PDB.Supported_Dictionary`:
> 
> ```
>  Data_Dictionary_RID |   Data_Dictionary_Category                             
> ---------------------+------------------------------
>  RID[2]              | ihm-extension
>  RID[4]              | mmcif_pdbx
> ```
> 
> At `export`, for the `PDB.Conform_Dictionary`, how do we know which `Category` from `PDB.Supported_Dictionary` to consider: `ihm-extension` or `mmcif_pdbx`?

**Comment by hongsudt** [comment]
@svoinea A few tasks left related to the data model changes: 
- For existing generated mmCIF, use the existing column which contained IHM version number to generate rows in the Conform_Dictionary
- Rename the psuedo-column to "Conform Dictionary"  which generates a comma separated list and the list should be sorted   
- The dictionary row name should be `<name> (v <version_number>)`

**Comment by brindakv** [comment]
@svoinea please confirm if this has been implemented.

**Comment by svoinea** [comment]
I confirm that it was implemented.

**Comment by brindakv** [comment]
@hongsudt please review and close.
