### ISSUE TITLE
update export mmcif script

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#71]
- ~validate the generated mmCIF and record errors if found (need mmCIF dict). Follow instructions on the wiki page~ We will move the validation to a separate issue.. 
- support dictionary versions: 
  - add data dictionary version (from PDB.Supported_Dictionary) in the exported mmCIF 
  - create/update Conform_Dictionary entries 
  - update annotation to show the supported dictionaries
  
Below is an example of audit_conform syntax. Here is the [example mmCIF file](https://pdb-dev.wwpdb.org/cif/PDBDEV_00000001.cif)

```
loop_
_audit_conform.dict_name
_audit_conform.dict_version
_audit_conform.dict_location
mmcif_pdbx.dic 5.311  http://mmcif.wwpdb.org/dictionaries/ascii/mmcif_pdbx_v50.dic
ihm-extension.dic 1.0    https://github.com/ihmwg/IHM-dictionary/blob/master/ihm-extension.dic
```

**Comment by brindakv** [comment]
Add a column `location` in the `Dictionary Name` [vocab](https://dev.pdb-dev.org/chaise/recordset/#99/Vocab:Data_Dictionary_Name@sort(RID)) table. 

```
mmcif_pdbx.dic http://mmcif.wwpdb.org/dictionaries/ascii/mmcif_pdbx_v50.dic
ihm-extension.dic    https://github.com/ihmwg/IHM-dictionary/blob/master/ihm-extension.dic
flr-extension.dic https://github.com/ihmwg/FLR-dictionary/blob/master/flr-extension.dic

```

**Comment by brindakv** [comment]
`struct` table should not be looped.

**Comment by hongsudt** [comment]
I think this is all done.. @brindakv please review and close.
