### ISSUE TITLE
Updating release process

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#73]
I have checked and the user `pdbihm` (who is running the backend process) is a member of the following groups: pdb-admin, pdb-curator, pdb-reader, pdb-submitter, pdb-writer

To automate the release process for structures in PDB-Dev, the following issues need to be addressed. 
  - Validate the final mmCIF file created using [cpp-dict-pack](https://github.com/rcsb/cpp-dict-pack). This requires the creation of the combined PDBx/mmCIF and IHM dictionaries. 
  - Automate the issue of accession code after curation. We need a generator that creates a unique accession code in the following format: PDBDEV_[8-digit-number]. Example: `PDBDEV_00000192`. Note: Exclude numbers `1-110` from this. 
    - Add a serial column (Accession_Serial) to the Entry table. This value can be used to compose the accession_code after the entry is released. 
    - Eventually, Accession_Serial should be a not null key. Need to figure out what to do with old entries. 
    - Serban: The new serial column `Accession_Serial` has now the `acls` set to `[pdb_admin, isrd_staff]` for the `select/insert/update` operations.
  - Extend the status to allow curator to signal that this entry is ready for release, which will then trigger the script to generate the final mmCIF (next bullet).  
    - mmCIF generation process, after validation, set status = `mmCIF CREATED`
    - After curator checks and is happy with the submission, manually change status = `SUBMISSION COMPLETE` (new term)
    - Add a script that look for `SUBMISSION COMPLETE`, then make access_code available (appending a prefix with Accession_Serial) and set status = HOLD
    - Curator manually changes the status = `RELEASE READY` (new term) to trigger the release process.
    - Release process: Add a script to regenerate the final mmCIF (e.g. add the released related metadata in the mmCIF file -- next bullet), then change the status = REL
    - `SUBMISSION COMPLETE` and `RELEASE READY` should only be accessed by `pdb-curator` and `pdb-admin`. 
    - Suggested values for the new  rows of the vocabulary `workflow_status` table:
```
        Name         |                        Description                        
---------------------+-----------------------------------------------------------
 SUBMISSION COMPLETE | The curator has checked and submission is complete.
 RELEASE READY       | The curator has triggered the release process.
```
- Keep track of files involved in failed cases:
    - Need a new table to track these files (Entry_Error_File: "This table keeps track of files related to failed mmCIF validation")
        - columns: Entry_RID, File_Type (validation_diag_log, validation_parser_log, mmCIF), File_Name, File_Bytes, File_MD5, File_URL
        - unique: Entry_RID, File_Type  
    - A vocab table for "Validation_File_Type"
      - columns: Name, Description 

```
         Name         |                        Description                        
---------------------+-----------------------------------------------------------
 validation_diag_log | Validation log file with mmCIF diagnostic errors
 validation_parser_log  | Validation log file with mmCIF parser errors
 mmCIF | mmCIF file generated based on the data in the database prior to the validation
```
     
The `hatrac` namespace: 

```
/hatrac/pdb/entry/
  - submitted/ 
    - image/<year>  -- RID, Entry_ID unavailable     --> entry.Image_File_URL
    - mmCIF/<year> -- RID, Entry_ID unavailable    --> entry.mmCIF_File_URL
  - <year>/<entry_ID>/
    - validation_error                           --> Entry_Error_File.File_URL
    - final_mmCIF                               --> System_Generated_mmCIF_File.File_URL
    - submitted_related_file                  --> Entry_Related_File.File_URL
    - submitted_starting_model            --> ihm_starting_model_details.mmCIF_File_URL

/hatrac/pdb/template:  -->  Entry_Related_File_Templates.File_URL
```

- Update the mmCIF file. The following records need to be included in the `mmCIF` file for release. The following blob should be after the "Audit_Conform" section. 
```
#
_pdbx_database_status.status_code                     REL --> Entry.Workflow_Status
_pdbx_database_status.entry_id                        PDBDEV_00000001 --> Entry.Accession_Code
_pdbx_database_status.deposit_site                    ?
_pdbx_database_status.process_site                    ?
_pdbx_database_status.recvd_initial_deposition_date   2016-08-31  --> entry RCT 
# 
_pdbx_audit_revision_history.ordinal                          1
_pdbx_audit_revision_history.data_content_type      'Structure model'
_pdbx_audit_revision_history.major_revision             1
_pdbx_audit_revision_history.minor_revision             0
_pdbx_audit_revision_history.revision_date               2016-08-31     --> current date (e.g. the time when the file is generated)  
# 
_pdbx_audit_revision_details.ordinal             1
_pdbx_audit_revision_details.revision_ordinal    1
_pdbx_audit_revision_details.data_content_type   'Structure model'
_pdbx_audit_revision_details.provider            repository
_pdbx_audit_revision_details.type                'Initial release'
_pdbx_audit_revision_details.description         ?
``` 
We need a mechanism to create the final mmCIF file for release, which should include the information above. The data for `_pdbx_database_status.status_code`, `_pdbx_database_status.entry_id `, `_pdbx_database_status.recvd_initial_deposition_date` and `_pdbx_audit_revision_history.revision_date` should be obtained from the catalog. This might require updating the data model itself to incorporate the necessary information. 

Additional requirement: The following items in the final generated mmCIF file need to be replaced with the newly issued accession code (`PDBDEV_XXXXXXXX`)
  - first line should be `data_<Entry.Accession_Code>` instead of `data_D_<RID>` 
  - value of `_entry.id` should be `<Entry.Accession_Code>`
  - value of `_struct.entry_id` should be `<Entry.Accession_Code>`
  - value of `_pdbx_database_status.entry_id ` should be `<Entry.Accession_Code>`
  - the mmCIF filename should be `<Entry.Accession_Code>`.cif
  - `struct` should not be looped

**Comment by svoinea** [comment]
@brindakv Following the instructions from the `README.md` file from https://github.com/rcsb/cpp-dict-pack, I was running:
```
git clone  --recurse-submodules  https://github.com/rcsb/cpp-dict-pack.git
mkdir build
cd build
cmake .. -DMINIMAL_DICTS=ON
cd build
mkdir PDBx
cd PDBx
wget http://mmcif.pdb.org/dictionaries/ascii/mmcif_pdbx_v50.dic
../bin/DictToSdb -ddlFile ../dicts/dict-mmcif_ddl/mmcif_ddl.dic       -dictFile mmcif_pdbx_v50.dic -dictSdbFile mmcif_pdbx_v50.sdb
```
The last command, raised the error:
```
-bash: ../bin/DictToSdb: No such file or directory
```
The content of the `../bin` directory is:
```
CreateDictObjFile.csh
CreateDictSdbFile.csh
Dict2XMLSchema.csh
DictToHTML.csh
WWPDBInstallSvn.csh
WWWProdInstall.csh
```
