### ISSUE TITLE
Molstar viewer

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#74]
[Molstar](https://molstar.org) is a web application for visualizing structures of macromolecules. For an example visualization, see [here](https://pdb-dev.wwpdb.org/view3d.html?PDBDEV_00000001). 

We can incorporate Molstar in the PDB-Dev Deriva catalog so that users can visualize the structures directly. 

The software is maintained in a public [Git repository](https://github.com/molstar/molstar).  

More information on embedding Molstar viewer: https://unpkg.com/browse/molstar@3.3.1/build/viewer/

Updated js, css and html files: https://github.com/informatics-isi-edu/protein-database/tree/master/scripts/molstar

**Comment by svoinea** [comment]
Additional files were needed:
 - bootstrap4.1.3.min.css
 - em-styles-cutdown.css
 - navbar.css

 - bootstrap3-typeahead.min.js
 - bootstrap4.1.3.min.js
 - jquery-3.3.1.min.js
 - popper1.12.9.min.js

For example, in the file `view3d.html`, there is this line:
```
                $(document).ready(on_ready); 
```
The `$` is defined in `jquery`.
All those files I was able to download them from `pdb-dev.wwpdb.org`.
However, there are still files missing.
See:
<img width="1165" alt="errors" src="https://user-images.githubusercontent.com/1609577/158497270-0623b4c6-750c-4455-88f8-201810f3b6d5.png">
Current view on `dev.pdb-dev.org`:
<img width="1834" alt="molstar" src="https://user-images.githubusercontent.com/1609577/158497380-6e7ff797-584f-4ea0-aeb5-31a0d7cbaa96.png">

**Comment by brindakv** [comment]
Python-ihm version is 0.23 on both staging and production catalogs.

**Comment by brindakv** [comment]
The issue with Molstar is in the `entity` table. `_entity.type` is of type ucode. Since we capitalize all ucode data items, we have it as `POLYMER`. mmCIF rules allow it. But Molstar expects this to be lowercase `polymer`.

**Comment by brindakv** [comment]
@svoinea Molstar version 3.6.1 has a fix for this issue: https://unpkg.com/browse/molstar@3.6.1/build/viewer/

Please make sure to download the raw js and css files from the link above.

**Comment by svoinea** [comment]
Done on catalog `99` under the commit # `73d0c4f`.

**Comment by brindakv** [comment]
Update molstar panel size to 800px x 700px

3D Visualization should be allowed for the following `Workflow Status`: `mmCIF CREATED`, `SUBMISSION COMPLETE`, `HOLD`, `RELEASE READY`, `REL`

Default text to be shown for the `3D Visualization` column when the structure cannot be visualized (i.e., all other status than those mentioned above): `3D Visualization is available after a compliant mmCIF file is created`

**Comment by svoinea** [comment]
Already moved to staging and production.
