### ISSUE TITLE
Bulk edit / delete

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#75]
When there are hundreds of rows in a table and the user wants to change the value of a particular column (e.g., `Restraint Type` column in the `Chemical Crosslinking Restraints` table) in all the rows, there is no easy way to do it via the GUI. 

The data is ingested via a CSV file. When the CSV file is re-uploaded with the modified data, the system throws an error because of duplicate keys.

**Comment by svoinea** [comment]
For data ingested via a CSV file, the backend script can be updated such that a `DELETE` operation will precede the `INSERT` operation.
The `DELETE` operation will be based on the value of the `structure_id`.

The GUI does not offer at this time a `bulk delete` in recordset.  

From what I understood, they are `working on adding a bulk “unlink” feature for pure and binary related entities in record page. It will be similar to the add pop up and would allow you to unlink the related entities`.

**Comment by hongsudt** [comment]
Bulk edit already exists. There is a pending issue to add bulk-delete in Chaise. I am moving this to block until chaise feature is added.

**Comment by hongsudt** [comment]
@jrchudy Will we enable the bulk delete and bulk unlink in the upcoming release?

**Comment by jrchudy** [comment]
Yes it should be available in the upcoming release.

We expect to have the bulk delete/unlink feature available for the next CFDE deadline at the end of January with a code freeze expected next Friday (January 14th).

**Comment by hongsudt** [comment]
@brindakv please review and close.. Bulk edit is available. Bulk delete will be in future release.

**Comment by brindakv** [comment]
@svoinea please confirm if the backend script has been updated so that DELETE operation precedes the INSERT operation for tables where data can be uploaded as CSV files.

**Comment by brindakv** [comment]
@svoinea testing on catalog 99 shows that DELETE operation does not precede the INSERT operation for tables where data can be uploaded as CSV files in `Entry_Related_File`.

**Comment by svoinea** [comment]
@brindakv What data should be deleted? There can be multiple `Entry_Related_File` records referencing an `entry`. Is it supposed that each table must be empty before loading into it the data from a CSV file?

**Comment by brindakv** [comment]
@svoinea Yes, the data in the specific table corresponding to `Entry_Related_File.File_Type` should be DELETED before INSERTING data from the newly uploaded csv/tsv file.

**Comment by svoinea** [comment]
I have added on catalog `99` the `DELETE` operation to precede the `INSERT` operation for tables where data can be uploaded as CSV files in `Entry_Related_File`.

**Comment by brindakv** [comment]
This will be tested along with #87.

**Comment by brindakv** [comment]
Looks good on Dev.
