### ISSUE TITLE
Rank the rows of Workflow Status

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#76]
Create a `Rank` column in the `Workflow Status` [Vocab table](https://dev.pdb-dev.org/chaise/recordset/#99/Vocab:workflow_status@sort(Rank,RID)) to rank the display of rows in the table.

**Comment by svoinea** [comment]
@brindakv I have added the `Rank` column and provided values for it, such that the rows are ordered ascending based on them.

If you have other preferences for the rows order, let me know.

**Comment by brindakv** [comment]
The ranks should follow the order in the workflow as follows: 

1. DRAFT
2. DEPO
3. RECORD READY
4. SUBMIT
5. mmCIF CREATED
6. SUBMISSION COMPLETE
7. HOLD
8. RELEASE READY
9. REL
10. ERROR
11. PROC
