### ISSUE TITLE
`audit_conform` should not be populated during ingest

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#78]
`audit_conform` mmCIF table is getting populated during ingest, even when it is not present in the input file. 

If it is present in the input mmCIF file, it should be populated. If not, it should be empty. 

Do not let the user edit this table through the frontend. 

For an example see [here](https://dev.pdb-dev.org/chaise/record/#50/PDB:entry/RID=1-PDCG).

**Comment by svoinea** [comment]
The `D_1-SKVR.cif` does NOT contain `audit_conform`.
However, the `make-mmcif.py` converts it in the `output.cif` that contains `audit_conform`:
```
grep audit_conform output.cif
_audit_conform.dict_location https://raw.githubusercontent.com/ihmwg/IHM-dictionary/b4fe8af/ihm-extension.dic
_audit_conform.dict_name ihm-extension.dic
_audit_conform.dict_version 1.09
```

**Comment by brindakv** [comment]
Keep `audit_conform` table in the database. But do not populate it on ingest (suppress).

**Comment by svoinea** [comment]
On catalog `99` on dev.pdb-dev.rg, from now on, the `audit_conform` records will not be added any more in the database.

The existing `audit_conform` records are now visible only to curators and admins.

**Comment by brindakv** [comment]
@svoinea Our plan was to retain the `audit_conform` table and populate it, but make it not visible to the users.

**Comment by svoinea** [comment]
On catalog `99` and `50` the `audit_conform` records are added but visible only to curators and admins.

**Comment by brindakv** [comment]
If the latest release of `python-ihm` is used (0.31) and if the updated [make-mmcif.py](https://github.com/ihmwg/python-ihm/blob/main/util/make-mmcif.py) is used, then `audit_conform` should not get populated on ingest. I would prefer to try this on `dev` to make sure it works as expected.

**Comment by brindakv** [comment]
Either keep `audit_conform` and populate it based on python-ihm data or completely delete the table from ErmREST.

**Comment by brindakv** [comment]
This looks good on catalog 99.
