### ISSUE TITLE
User access

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#8]
Curators should have access to all entries, whereas depositors should only be able to access their own.

**Comment by hongsudt** [comment]
@carlkesselman can you make @brindakv admin of pdb groups?

**Comment by hongsudt** [comment]
Please allow isrd_staff and isrd_testers at least writer access to the catalog.

**Comment by svoinea** [comment]
The `isrd_staff` group was already `owner` of the catalog.
I have added the `isrd_testers` group in the catalog `5` with `write` and `create` access.
