### ISSUE TITLE
Fix accession serial of non-released submissions

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#82]
These entries are those were recently submitted to the pdbdev system and were not released yet..
The constraints are: 
```
Accession_Code is NULL and ID NOT ~ 'PDBDEV_'
``` 
which should result to 17 rows. 

 - For these 17 entries, update  `Accession Serial` to start from 111. 
 - Reset the serial counter to 128 going forward
  
 - Model/annotation changes: 
   - Make Accession_Serial unique
   - Make Accession_Code unique. 
   - Make accession serial in the entry table visible to curators only (ACL, chaise). HT: Let's not try to edit this field yet.

**Comment by svoinea** [comment]
The `17` rows were updated:
```
_ermrest_catalog_1=> select "RID", id,"Accession_Serial",accession_code from entry where "Accession_Serial">=112;
  RID   |    id    | Accession_Serial | accession_code  
--------+----------+------------------+-----------------
 1-SD46 | D_1-SD46 |              112 | PDBDEV_00000112
 1-S8A6 | D_1-S8A6 |              113 | 
 1-RPZ4 | D_1-RPZ4 |              114 | 
 1-Q7QP | D_1-Q7QP |              115 | 
 1-RJSW | D_1-RJSW |              116 | 
 1-RPZ6 | D_1-RPZ6 |              117 | 
 1-RPZC | D_1-RPZC |              118 | 
 1-NR0J | D_1-NR0J |              119 | 
 1-NK7M | D_1-NK7M |              120 | 
 1-NQPA | D_1-NQPA |              121 | 
 1-S87R | D_1-S87R |              122 | 
 1-N4AY | D_1-N4AY |              123 | 
 1-RP1A | D_1-RP1A |              124 | 
 1-NA4Y | D_1-NA4Y |              125 | 
 1-NF8W | D_1-NF8W |              126 | 
 1-P7V0 | D_1-P7V0 |              127 | 
 1-PBTC | D_1-PBTC |              128 | 
(17 rows)
```
The serial counter was reset to `128`:
```
_ermrest_catalog_1=> select last_value from "entry_Accession_Serial_seq";
 last_value 
------------
        128
(1 row)
```

**Comment by svoinea** [comment]
Created the `unique` constraint for the `Accession_Serial` and `accession_code` columns:
```
    "entry_Accession_Serial_primary_key" UNIQUE CONSTRAINT, btree ("Accession_Serial")
    "entry_accession_code_primary_key" UNIQUE CONSTRAINT, btree (accession_code)
```

**Comment by brindakv** [comment]
@svoinea update the same on `dev` and `staging`.

**Comment by hongsudt** [comment]
I think @svoinea  has applied the changes to all envs. @brindakv please check.

**Comment by brindakv** [comment]
Accession serial in the entry table is not visible to curators/admin.

**Comment by svoinea** [comment]
Should be visible now on catalog `99`.

**Comment by brindakv** [comment]
Yes, this is visible on catalog `99` and can be implemented on staging and production.

**Comment by svoinea** [comment]
`Accession_Serial` is already visible on staging and production.

TO DO: Fix the values of the `Accession_Serial` on production.

**Comment by brindakv** [comment]
Make `Accession_Serial` visible only to `pdb-admin` and `pdb-curator`. At present it is visible to `pdb-submitter` as well.

**Comment by svoinea** [comment]
At present, it is visible to `pdb_admin` and `isrd_staff`:

https://data.pdb-dev.org/ermrest/catalog/1/schema/PDB/table/entry/column/Accession_Serial/acl/

```
{
  "insert": [
    "https://auth.globus.org/0b98092c-3c41-11e9-a8c8-0ee7d80087ee",
    "https://auth.globus.org/176baec4-ed26-11e5-8e88-22000ab4b42b"
  ],
  "select": [
    "https://auth.globus.org/0b98092c-3c41-11e9-a8c8-0ee7d80087ee",
    "https://auth.globus.org/176baec4-ed26-11e5-8e88-22000ab4b42b"
  ],
  "update": [
    "https://auth.globus.org/0b98092c-3c41-11e9-a8c8-0ee7d80087ee",
    "https://auth.globus.org/176baec4-ed26-11e5-8e88-22000ab4b42b"
  ]
}
```
where:
```
pdb_admin = "https://auth.globus.org/0b98092c-3c41-11e9-a8c8-0ee7d80087ee"
isrd_staff = "https://auth.globus.org/176baec4-ed26-11e5-8e88-22000ab4b42b"
```
I suppose your request is to add `pdb-curator` in the list of `acls`.

**Comment by brindakv** [comment]
My request is that this not be visible to `pdb-submitter`, `pdb-user`.

**Comment by brindakv** [comment]
![Screen Shot 2022-05-26 at 2 22 39 PM](https://user-images.githubusercontent.com/15000874/170554374-492c269d-6f5c-4069-b4e4-0c3fdc1206aa.png)
