### ISSUE TITLE
Add release date for each entry

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#85]
We can either add `release_date` to the `entry` table or follow mmCIF for full release-related metadata. 

In case of the latter, data model needs be updated to include audit records from mmCIF: 
 - `pdbx_database_status`
 - `pdbx_audit_revision_history`
 - `pdbx_audit_revision_details`

```
#
_pdbx_database_status.status_code                     REL --> Entry.Workflow_Status
_pdbx_database_status.entry_id                        PDBDEV_00000001 --> Entry.Accession_Code
_pdbx_database_status.deposit_site                    ?
_pdbx_database_status.process_site                    ?
_pdbx_database_status.recvd_initial_deposition_date   2016-08-31  --> entry RCT 
# 
_pdbx_audit_revision_history.ordinal                          1
_pdbx_audit_revision_history.data_content_type      'Structure model'
_pdbx_audit_revision_history.major_revision             1
_pdbx_audit_revision_history.minor_revision             0
_pdbx_audit_revision_history.revision_date               2016-08-31     --> Release date  
# 
_pdbx_audit_revision_details.ordinal             1
_pdbx_audit_revision_details.revision_ordinal    1
_pdbx_audit_revision_details.data_content_type   'Structure model'
_pdbx_audit_revision_details.provider            repository
_pdbx_audit_revision_details.type                'Initial release'
_pdbx_audit_revision_details.description         ?
```

**Comment by brindakv** [comment]
In the `entry` table, add the columns:
 - Notes (markdown)
 - Release_Date (date)

Need a CSV/JSON file with accession code, deposition date (for entry RCT), release date for all legacy entries (including the 33 in the system). 

For later: consider adding `major and minor versions` and `deprecate` columns in the `entry` table.

**Comment by brindakv** [comment]
Depends on #83

**Comment by svoinea** [comment]
The `Notes` and the `Released_Date` columns are visible in the `detailed` and `edit` views.

**Comment by svoinea** [comment]
Added the `Notes` and `Released_Date` columns also on staging and production.

**Comment by svoinea** [comment]
Done on catalog `99`.

**Comment by brindakv** [comment]
Looks good on catalog 99.
