### ISSUE TITLE
Automated emails 

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#89]
Send automated emails to `pdb-curator` group when workflow status changes to `Record Ready` and `mmCIF Created`

**Comment by svoinea** [comment]
@brindakv Please provide the list with the emails of the curators that will receive the automated emails.

**Comment by svoinea** [comment]
Updated the code such that the curators are receiving automated emails when workflow status changes to `Record Ready` and `mmCIF Created`.

**Comment by monica81567** [comment]
@svoinea can please change the email subject line to include the RID id.  For example:
Subject line:  PDB RECORD READY 2-6YS4

**Comment by brindakv** [comment]
Done on catalog `99`

**Comment by brindakv** [comment]
Consider separating admin and curator email lists. Right now they are both pointing to [pdb-ihm@.wwpdb.org](mailto:pdb-ihm@.wwpdb.org).

**Comment by brindakv** [comment]
Monica and I are not getting automated emails from the system anymore. We have missed processing several entries in the past week because no emails were received.

**Comment by svoinea** [comment]
The ISI email server I am using does not like the `pdb-ihm@wwpdb.org` address.
It did not report any error, but it did not sent the mail.
Nor myself was receiving it.

I have reverted the email receivers by specifying the enumeration of our email addresses.

**Comment by svoinea** [comment]
The email works now by using the `pdb-ihm@wwpdb.org` address.
