### ISSUE TITLE
Link to CSV template files needs to be changed

### ISSUE THREAD

**Issue by monica81567** [informatics-isi-edu/protein-database#91]
The uploaded restraint files section says "Templates for the CSV files can be downloaded from https://pdb.isrd.isi.edu/chaise/recordset/#99/PDB:Entry_Related_File_Templates?pcid=navbar/record&ppid=2kcj1s7w2qrm1zyk1qju2ne7"

When I copy and paste the link to a web browser, the page says:
Web services on "pdb.isrd.isi.edu" are deprecated. Please direct all PDB-Dev requests to [data.pdb-dev.org](https://data.pdb-dev.org/)

Please change the link to https://data.pdb-dev.org/chaise/recordset/#1/PDB:Entry_Related_File_Templates@sort(RID)

**Comment by svoinea** [comment]
Should be fixed at this time.

**Comment by monica81567** [comment]
New link works!  Thanks for the quick update.

**Comment by monica81567** [comment]
Closing this issue.
