### ISSUE TITLE
Update citation information during release process

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#94]
Add primary publication information in the workflow before release. 

- [x] This requires regeneration of mmCIF file with the database contents for that entry after curator changes status to `Release Ready`. 

- [x] Release metadata needs to be included in the mmCIF file (currently added statically) -- already taken care of by the processing script.

**Comment by svoinea** [comment]
Done on catalog `99`.

**Comment by brindakv** [comment]
This works as expected on catalog 99. 

@svoinea if an entry status is changed to `Release Ready` on a different date (after it has been released), do `_pdbx_audit_revision_history.revision_date` and `entry.Release_Date` retain the original release date?

**Comment by svoinea** [comment]
The `entry.Release_Date` is set to the current date ONLY if it is `NULL`. If it was already set, it retains the original value.
`_pdbx_audit_revision_history.revision_date` is just taking the value of the `entry.Release_Date`.

**Comment by brindakv** [comment]
@svoinea Thanks for clarifying. I will test this again tomorrow (on a different date) and confirm.

**Comment by brindakv** [comment]
This works as expected and can be moved to production.
