### ISSUE TITLE
Add RCB (and RMB) to the detail Entry page and add link to user details through RCB

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#96]

**Comment by svoinea** [comment]
@brindakv Is it OK to have in the detail page just the email for the `RCB` and `RMB`?
Having the link to the user details leads to display too much extra info which I think it is not necessary.
For example, it includes all the records from all the tables that are referencing that user.  
I think that it might be enough if we have in the compact view the user full name and in the detailed view the user email.

**Comment by brindakv** [comment]
@svoinea Just the email is fine for RCB and RMB on the detail page.

**Comment by svoinea** [comment]
Done on catalog `99`.

**Comment by brindakv** [comment]
RCB is correct. RMB shows `pdb-ihm (serban.voinea+pdbihm@gmail.com)`. Should this be changed to `pdb-ihm@wwpdb.org`?

**Comment by svoinea** [comment]
The backend is runnig with the `pdbihm` user that is registered in Globus with the `serban.voinea+pdbihm@gmail.com` email. The `pdbihm` user was created by myself in Globus, which explains its email value.
`pdb-ihm@wwpdb.org` is the receiver of the emails and it is not registered in Globus.

**Comment by brindakv** [comment]
Thanks for clarifying @svoinea. Looks good and can be moved to production.

**Comment by brindakv** [comment]
Do not show email address for RMB.

**Comment by svoinea** [comment]
I have removed the email address from RMB in the detailed context of the entry.

**Comment by brindakv** [comment]
Looks good @svoinea. Thanks.
