### ISSUE TITLE
System generated mmCIF file has wrong struct_ref.db_name

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#98]
The system generated mmCIF file has wrong `struct_ref.db_name` value compared to the value in ErmRest. See example `2-6ZSA` in production catalog.

**Comment by svoinea** [comment]
@brindakv The `PDB` value was created at `2022-07-12 12:56:06.397567-07`, while the mmCIF file was created on `Jul  5 14:32`.

**Comment by brindakv** [comment]
Thank you.
