### ISSUE TITLE
Make `Polymeric Entities` table editable by curators

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#99]
At present, `entity_poly` table is not editable by curators (it was a requirement earlier). However, there is an issue with entry `2-6ZSA`, which needs to be addressed. Access control for this table needs to be updated so that it can be editable by curators (not by submitters).

**Comment by svoinea** [comment]
Should be done at this time on `dev`, `staging` and `production`.

**Comment by brindakv** [comment]
The same has been done with the `chem_comp` table as well.

**Comment by brindakv** [comment]
The same needs to be applied to `ihm_model_list`.

**Comment by svoinea** [comment]
Already done for `ihm_model_list` on `dev`, `staging` and `production`.
